### PR TITLE
Fixes #5195 - USING INDEX hints breaks some queries

### LINKED ISSUE #5195: [Cypher][2.*] Issues with queries that include all of the following: UNION, USING and ID()
When a query includes all the following keywords (`UNION`, `USING`, `ID()`), it results in a `NoSuchElementException key not found: SymbolUse(id@*)`.

As an example:

```
MATCH (actorNode:PERSON {id:'deev'})-[:PUBLISH]->(objectNode:ACTIVITY)
USING INDEX actorNode:PERSON(id)
RETURN ID(objectNode) as id

UNION

MATCH (actorNode:PERSON {id:'deev'})-[:PUBLISH]->(objectNode:ACTIVITY)
RETURN ID(objectNode) as id
```

This gives me a `key not found: SymbolUse(id@100)`. I've tried it in 2.2.1, 2.2.2, and in the 2.3.0-M02, all giving me the same error (although the `id@*` value changes).

Removing any of the keywords fixes the problem. That is to say...

```
MATCH (actorNode:PERSON {id:'deev'})-[:PUBLISH]->(objectNode:ACTIVITY)
USING INDEX actorNode:PERSON(id)
RETURN ID(objectNode) as id
```

```
MATCH (actorNode:PERSON {id:'deev'})-[:PUBLISH]->(objectNode:ACTIVITY)
USING INDEX actorNode:PERSON(id)
RETURN objectNode.id

UNION

MATCH (actorNode:PERSON {id:'deev'})-[:PUBLISH]->(objectNode:ACTIVITY)
RETURN objectNode.id
```

```
MATCH (actorNode:PERSON {id:'deev'})-[:PUBLISH]->(objectNode:ACTIVITY)
RETURN objectNode.id

UNION

MATCH (actorNode:PERSON {id:'deev'})-[:PUBLISH]->(objectNode:ACTIVITY)
RETURN objectNode.id
```

All of the queries above work just fine :)

### PR DESCRIPTION
**Pull request by systay**
Hints using already existing identifiers could break semantic checking.

### CODE REVIEW

File: community/cypher/cypher/src/test/scala/org/neo4j/cypher/UsingAcceptanceTest.scala [hunk 1]
```diff
@@ -208,4 +208,17 @@ class UsingAcceptanceTest extends ExecutionEngineFunSuite with NewPlannerTestSup
 
     e.getMessage should startWith("Multiple hints for same identifier are not supported")
   }
+
+  test("UNION and USING together should not be problematic") {
```
Comment (davidegrohmann) [inline community/cypher/cypher/src/test/scala/org/neo4j/cypher/UsingAcceptanceTest.scala]: `UNION`?

Comment (systay) [inline community/cypher/cypher/src/test/scala/org/neo4j/cypher/UsingAcceptanceTest.scala]: It made sense at the time. I fix. :)
