### PR TITLE
Convert Cypher parameter types

### LINKED ISSUE #7115: [3.0][Procedure] Can't use Long safely as procedure argument type
**Neo4j Version:** 3.0.1
**Operating System:** OSX
**API:** Browser/PHP

In the below example, using Long as procedure argument's type is not safe, because : 
1. It is treated as long when you pass a number as procedure call argument.
2. It is treated as integer when you pass a the same number as query parameter and use the parameter as procedure call parameter

Which means that we can't use a type of `Integer` or `Long` as procedure argument type, because the type coerced differs from Cypher inline vs Query parameter.
### Steps to reproduce

``` java
package proc;

import org.neo4j.procedure.Context;
import org.neo4j.procedure.Name;
import org.neo4j.procedure.Procedure;

import java.util.stream.Stream;

public class LongInt {

    @Procedure
    public Stream<Record> test(@Name("object") Object object) {
        return Stream.of(new Record(object.getClass()));
    }

    public class Record {

        public final Object value;

        public Record(Object value) {
            this.value = value;
        }

    }
}
```

Procedure parameter passed inline in the Cypher query

``` java
@Test
public void testIt1() {
  Driver driver = GraphDatabase.driver( "bolt://localhost" );
  Session session = driver.session();
  StatementResult rs = session.run("CALL proc.test(500)");
  rs.consume();
  session.close();
  driver.close();

  // Returns class java.lang.Long
}
```

Procedure parameter passed from query parameters map // Procedure parse it as Integer

``` java
@Test
public void testIt2() {
  Driver driver = GraphDatabase.driver( "bolt://localhost" );
  Session session = driver.session();
  Map<String, Object> params = new HashMap<>();
  params.put("v", 500);
  StatementResult rs = session.run("CALL proc.test({v})", params);
  rs.consume();
  session.close();
  driver.close();

  // Returns class java.lang.Integer
}
```

### PR DESCRIPTION
**Pull request by henriknyman**
Fixes #7115 - Can't use Long safely as procedure argument type

- Converts Float to Double
- Converts all other Number types to Long
- Converts Character to String (this breaks backward compatibility tests)
- Converts values of Array, List and Map recursively
(including primitive arrays)
- Fix issue with materialization of Map results in compiled runtime

NOTE: This means that you can no longer use Cypher in embedded Neo4j to
store non-Cypher type property values.

### CODE REVIEW

**Comment by henriknyman** [comment]
It is still unclear to me wether we really want to do the full conversion without having a replacement mechanism in place (e.g. something like user defined value types).

File: community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/ParameterValuesAcceptanceTest.scala [hunk 1]
```diff
@@ -67,4 +67,113 @@ class ParameterValuesAcceptanceTest extends ExecutionEngineFunSuite with NewPlan
...
+  }
+
+  test("array parameters should be transformed to cypher types") {
+    def echo(any: Any): Array[_] = {
+      executeWithAllPlannersAndRuntimesAndCompatibilityMode("RETURN {p} AS p", "p" -> any)
+        .columnAs[Array[_]]("p").next()
+    }
+
+    def echoNoCompatibility(any: Any): Array[_] = {
+      executeWithAllPlanners("RETURN {p} AS p", "p" -> any)
```
Comment (Mats-SX) [inline community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/ParameterValuesAcceptanceTest.scala:90]: You can use the new parameter syntax for this one: `$p`

File: community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/ParameterValuesAcceptanceTest.scala [hunk 2]
```diff
@@ -67,4 +67,113 @@ class ParameterValuesAcceptanceTest extends ExecutionEngineFunSuite with NewPlan
...
+    echoNoCompatibility(Array[java.lang.Character]('a')).foreach(_ shouldBe a[java.lang.String])
+
+    // Nested array
+    echo(Array[Array[Byte]](Array(42.asInstanceOf[Byte]))).foreach { x =>
+      x shouldBe a[Array[AnyRef]]
+      x.asInstanceOf[Array[_]].foreach(_ shouldBe a[java.lang.Long])
+    }
+  }
+
+  test("list parameters should be transformed to cypher types") {
```
Comment (Mats-SX) [inline community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/ParameterValuesAcceptanceTest.scala:120]: List _elements_, right?

File: community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/ParameterValuesAcceptanceTest.scala [hunk 3]
```diff
@@ -67,4 +67,113 @@ class ParameterValuesAcceptanceTest extends ExecutionEngineFunSuite with NewPlan
...
+    def echo(any: Any): Iterable[_] = {
+      executeWithAllPlannersAndRuntimesAndCompatibilityMode("RETURN {p} AS p", "p" -> any)
+        .columnAs[Iterable[_]]("p").next()
+    }
+
+    def echoNoCompatibility(any: Any): Iterable[_] = {
+      executeWithAllPlanners("RETURN {p} AS p", "p" -> any)
```
Comment (Mats-SX) [inline community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/ParameterValuesAcceptanceTest.scala:127]: Also here

**Review by Mats-SX — APPROVED** [review]
Looks good I think
