### PR TITLE
Fix rule planner index seek node fetch strategy

### LINKED ISSUE #5768: Cypher problem with comparing coalesced value with index
Hi,

This has stopped working for me now on 2.3.0:

```
MATCH (n:MyNodes)
SET n.temp = 99
WITH count(n) as a_way_to_continue
MATCH (m:MyNodes)
WHERE m.CurrentBalance>coalesce(m.MinimumAmount,0)
RETURN m
```

it returns:
    _Unknown identifier 'm'._

```
:schema

Indexes
  ON :MyNodes(CurrentBalance) ONLINE  

No constraints
```

Note: MinimumAmount is not always populated

However, the query runs as expected (returns rows) when I change the statement in any of the following ways:
- Drop the index :MyNodes(CurrentBalance)
- Remove the SET command
- Replace the coalesce function with either of it's two arguments

### PR DESCRIPTION
**Pull request by henriknyman**
Fixes #5768
A node symbol dependency on the right-hand side of a predicate
could erroneously be declared as met

### CODE REVIEW

**Comment by Mats-SX** [comment]
This should be a null-forward merge due to #5808.

File: community/cypher/cypher/src/test/scala/org/neo4j/cypher/IndexUsageAcceptanceTest.scala [hunk 1]
```diff
@@ -125,6 +125,30 @@ class IndexUsageAcceptanceTest extends ExecutionEngineFunSuite with NewPlannerTe
     result.toList should equal(List(Map("p" -> null, "placeName" -> null)))
   }
 
+  test("should not use indexes when RHS of property comparison depends on the node searched for (equality)") {
```
Comment (Mats-SX) [inline community/cypher/cypher/src/test/scala/org/neo4j/cypher/IndexUsageAcceptanceTest.scala:128]: The test says 'should not use indexes' but it makes no such assertion. I'd say we add one or change the test name.

**Comment by pontusmelke** [comment]
I am confused about the two PRs, why not just one that is forward merged?
