### PR TITLE
Merge on node with unique constraint must handle multiple labels

### LINKED ISSUE #5631: Merging nodes with unique constraints does not respect label pattern
```
neo4j-sh (?)$ create constraint on (n:TEST) assert n.title is unique;
+-------------------+
| No data returned. |
+-------------------+
Unique constraints added: 1
262 ms
neo4j-sh (?)$ create (test:TEST:A {title : "test"});
+-------------------+
| No data returned. |
+-------------------+
Nodes created: 1
Properties set: 1
Labels added: 2
322 ms
neo4j-sh (?)$ merge (test:TEST:B {title : "test"}) return labels(test);
+--------------+
| labels(test) |
+--------------+
| ["TEST","A"] |
+--------------+
1 row
202 ms
```

The expected output of the last command would be to throw a `Unique constraint violation`. But instead, it wrongly matches the previously created node with labels `"TEST" and "A"`.

I tried with neo4j version 2.2.2 and version 2.3.0-M03.

### PR DESCRIPTION
**Pull request by pontusmelke**
Merge is not properly handling matching on multiple labels when there
is a unique constraint on one of the labels being matched on.

fixes #5631

Also added an update to `CHANGES.txt` which was missed in https://github.com/neo4j/neo4j/pull/5626

### CODE REVIEW

File: community/cypher/cypher/src/test/scala/org/neo4j/cypher/MergeNodeAcceptanceTest.scala [hunk 1]
```diff
@@ -506,4 +507,33 @@ class MergeNodeAcceptanceTest extends ExecutionEngineFunSuite with QueryStatisti
 
     result.executionPlanDescription().toString should not include "Eager"
   }
+
+  test("merge must properly handle multiple labels") {
```
Comment (pontusmelke) [inline community/cypher/cypher/src/test/scala/org/neo4j/cypher/MergeNodeAcceptanceTest.scala:511]: This test wasn't failing, just added for completeness.

File: community/cypher/cypher/src/test/scala/org/neo4j/cypher/MergeNodeAcceptanceTest.scala [hunk 2]
```diff
@@ -506,4 +507,33 @@ class MergeNodeAcceptanceTest extends ExecutionEngineFunSuite with QueryStatisti
...
+    createLabeledNode(Map("prop" -> 42), "L", "A")
+
+    val result = execute("merge (test:L:B {prop : 42}) return labels(test) as labels")
+
+    assertStats(result, nodesCreated = 1, propertiesSet = 1, labelsAdded = 2)
+    result.toList should equal(List(Map("labels" -> List("L", "B"))))
+  }
+
+  test("merge with an index must properly handle multiple labels") {
```
Comment (pontusmelke) [inline community/cypher/cypher/src/test/scala/org/neo4j/cypher/MergeNodeAcceptanceTest.scala:520]: This test wasn't failing, just added for completeness.
