### PR TITLE
Fixes issue with import tool manual references

### LINKED ISSUE #5885: Error message pointing at wrong URL
Hey there!
While creating fake data to try out neo4j 2.3 EE, i create a relationship file without TYPE field, so import gave me a

```
Relationship missing mandatory field 'TYPE', read more about relationship format in the manual:  http://neo4j.com/docs/2.3.0,c6c3a7b/import-tool-header-format.html#import-tool-header-format-rels
```

which is fair enough, but URL goes 404

### PR DESCRIPTION
**Pull request by tinwelint**
in the event of errors that manual could provide more information about.
Link used kernel version including git hash. Changed to only use version part.

Fixes #5885

### CODE REVIEW

File: community/import-tool/src/test/java/org/neo4j/tooling/ImportToolTest.java [hunk 1]
```diff
@@ -761,7 +761,7 @@ public void shouldPrintReferenceLinkOnDataImportErrors() throws Exception
         shouldPrintReferenceLinkAsPartOfErrorMessage( nodeIds(),
                 IteratorUtil.iterator( new RelationshipDataLine( "1", "", "type", "name" ) ),
                 "Relationship missing mandatory field 'END_ID', read more about relationship " +
-                "format in the manual:  http://neo4j.com/docs/" + Version.getKernelVersion() +
+                "format in the manual:  http://neo4j.com/docs/" + Version.getKernel().getReleaseVersion() +
```
Comment (spacecowboy) [inline community/import-tool/src/test/java/org/neo4j/tooling/ImportToolTest.java:764]: Shouldn't this change also be applied to line `769`?

Comment (tinwelint) [inline community/import-tool/src/test/java/org/neo4j/tooling/ImportToolTest.java:764]: Damn straight. Fixed now
