### PR TITLE
Better error handling for percentileCont and percentileDisc

### LINKED ISSUE #5432: Percentile should throw InvalidArgumentException immediately on incorrect argument value
I tried to compute a percentile without paying too much attention to the docs (used 95 instead of 0.95):

Instead of telling me the correct value range for `{percentile}`, the function computation started (and took quite a bit of time), and threw `"java.lang.IndexOutOfBoundsException: 1231999804`, which I traced back to the `PercentileFunction`:

```
val floatIdx = perc * (count - 1)
val floor = floatIdx.toInt
val ceil = math.ceil(floatIdx).toInt
if(ceil == floor || floor == count - 1) temp(floor)
 // floor == 1231999804 on the next line
else asDouble(temp(floor)) * (ceil - floatIdx) + asDouble(temp(ceil)) * (floatIdx - floor)
```

If the function was fail-fast and checked the arguments, it wouldn't consume so much resources just to throw an internal exception.

### PR DESCRIPTION
**Pull request by pontusmelke**
Instead of failing at runtime `percentileCont` and `percentileDisc`
now fails in semantic checking when the provided percentile is not
in the valid range.

fixes #5432

### CODE REVIEW

File: community/cypher/cypher/src/test/scala/org/neo4j/cypher/SemanticDeleteAcceptanceTest.scala [hunk 1]
```diff
@@ -40,15 +40,16 @@ class SemanticDeleteAcceptanceTest extends ExecutionEngineFunSuite with PatternG
...
-        updateWithBothPlanners(s"MATCH $patternString DELETE ${identifiers.mkString(",")} RETURN count(*)")
-
-        //now db should be empty
-        executeWithAllPlanners("MATCH () RETURN count(*) AS c").toList should equal(List(Map("c" -> 0)))
+        withClue(s"failing on pattern $patternString") {
+          //update
+          updateWithBothPlanners(s"CREATE $patternString")
+          //delete
+          val identifiers = findAllRelationshipNames(pattern) ++ findAllNodeNames(pattern)
+          updateWithBothPlanners(s"MATCH $patternString DELETE ${identifiers.mkString(",")} RETURN count(*)")
```
Comment (Mats-SX) [inline community/cypher/cypher/src/test/scala/org/neo4j/cypher/SemanticDeleteAcceptanceTest.scala:48]: Let's drop `RETURN` since we can't assert on the result anyway.

File: community/cypher/acceptance/src/test/scala/org/neo4j/internal/cypher/acceptance/FunctionsAcceptanceTest.scala [hunk 2]
```diff
@@ -219,6 +219,23 @@ class FunctionsAcceptanceTest extends ExecutionEngineFunSuite with NewPlannerTes
...
+    createNode("prop" -> 10.0)
+    createNode("prop" -> 20.0)
+    createNode("prop" -> 30.0)
 
+    executeScalarWithAllPlanners[Double]("MATCH (n) RETURN percentileDisc(n.prop, 0.0)") should equal (10.0 +- 0.1)
+    executeScalarWithAllPlanners[Double]("MATCH (n) RETURN percentileDisc(n.prop, 0.5)") should equal (20.0 +- 0.1)
+    executeScalarWithAllPlanners[Double]("MATCH (n) RETURN percentileDisc(n.prop, 1.0)") should equal (30.0 +- 0.1)
+  }
+
+  test("percentileCont should work in the valid range") {
```
Comment (Mats-SX) [inline community/cypher/acceptance/src/test/scala/org/neo4j/internal/cypher/acceptance/FunctionsAcceptanceTest.scala:232]: What about negative acceptance tests? Ie, asserting that invalid values throw the expected error?

File: community/cypher/cypher/src/test/scala/org/neo4j/cypher/SemanticDeleteAcceptanceTest.scala [hunk 3]
```diff
@@ -61,15 +62,16 @@ class SemanticDeleteAcceptanceTest extends ExecutionEngineFunSuite with PatternG
...
-        updateWithBothPlanners(s"MATCH $patternString DETACH DELETE ${identifiers.mkString(",")} RETURN count(*)")
-
-        //now db should be empty
-        executeWithAllPlanners("MATCH () RETURN count(*) AS c").toList should equal(List(Map("c" -> 0)))
+        withClue(s"failing on pattern $patternString") {
+          //update
+          updateWithBothPlanners(s"CREATE $patternString")
+          //delete
+          val identifiers = findAllNodeNames(pattern)
+          updateWithBothPlanners(s"MATCH $patternString DETACH DELETE ${identifiers.mkString(",")} RETURN count(*)")
```
Comment (Mats-SX) [inline community/cypher/cypher/src/test/scala/org/neo4j/cypher/SemanticDeleteAcceptanceTest.scala:70]: Remove `RETURN`

File: community/cypher/frontend-3.0/src/main/scala/org/neo4j/cypher/internal/frontend/v3_0/ast/Function.scala [hunk 4]
```diff
@@ -182,4 +182,26 @@ abstract class AggregatingFunction extends Function {
...
       SemanticError(s"Invalid use of aggregating function $name(...) in this context", invocation.position)
     } chain invocation.arguments.semanticCheck(ctx) chain semanticCheck(ctx, invocation)
+
+
+  /*
+   * Checks so that the expression is in the range [min, max]
+   */
+  protected def checkRange(expression: Expression, min: Double, max: Double): SemanticCheck = {
+    expression match {
+      case d: DoubleLiteral if d.value >= min || d.value <= max =>
```
Comment (Mats-SX) [inline community/cypher/frontend-3.0/src/main/scala/org/neo4j/cypher/internal/frontend/v3_0/ast/Function.scala]: This must be `&&`.

File: community/cypher/frontend-3.0/src/main/scala/org/neo4j/cypher/internal/frontend/v3_0/ast/Function.scala [hunk 5]
```diff
@@ -182,4 +182,26 @@ abstract class AggregatingFunction extends Function {
...
+      case d: DoubleLiteral =>
+        SemanticError(s"Invalid input '${d.value}' is not a valid argument, must be a number in the range 0.0 to 1.0",
+          d.position)
+      case l: Literal =>
+        SemanticError(s"Invalid input '${
+          l.asCanonicalStringVal
+        }' is not a valid argument, must be a number in the range 0.0 to 1.0", l.position)
+
+      //for other types we'll have to wait until runtime to fail
+      case _ => SemanticCheckResult.success
```
Comment (Mats-SX) [inline community/cypher/frontend-3.0/src/main/scala/org/neo4j/cypher/internal/frontend/v3_0/ast/Function.scala:206]: Isn't it possible for some integer literal to appear here, where we could check the bounds?

File: community/cypher/cypher/src/test/scala/org/neo4j/cypher/SemanticDeleteAcceptanceTest.scala (hunk 1 above)
Comment (pontusmelke) [inline community/cypher/cypher/src/test/scala/org/neo4j/cypher/SemanticDeleteAcceptanceTest.scala:48]: No we should not do that, doing exactly that has caused us a ton of errors with eagerness.  `updateWithBothPlanners` asserts that both rule planner and cost planner returns the same thing.

File: community/cypher/cypher/src/test/scala/org/neo4j/cypher/SemanticDeleteAcceptanceTest.scala (hunk 3 above)
Comment (pontusmelke) [inline community/cypher/cypher/src/test/scala/org/neo4j/cypher/SemanticDeleteAcceptanceTest.scala:70]: no, see reason above. but let's try to always return in these types of queries it gives us one more place to find errors.

File: community/cypher/acceptance/src/test/scala/org/neo4j/internal/cypher/acceptance/FunctionsAcceptanceTest.scala (hunk 2 above)
Comment (pontusmelke) [inline community/cypher/acceptance/src/test/scala/org/neo4j/internal/cypher/acceptance/FunctionsAcceptanceTest.scala:232]: they live in `SemanticErrorAcceptanceTests`

File: community/cypher/frontend-3.0/src/main/scala/org/neo4j/cypher/internal/frontend/v3_0/ast/Function.scala (hunk 5 above)
Comment (pontusmelke) [inline community/cypher/frontend-3.0/src/main/scala/org/neo4j/cypher/internal/frontend/v3_0/ast/Function.scala:206]: I renamed the method, it sounded more general than what it is. It checks so that the number is in the range `[0.0, 1.0]` which not many integers are but you caught the bug that we should probably allow `percentileDisc(n.prop, 0)` and `percentileProp(n.prop, 1)`, :+1:

File: community/cypher/acceptance/src/test/scala/org/neo4j/internal/cypher/acceptance/FunctionsAcceptanceTest.scala (hunk 2 above)
Comment (Mats-SX) [inline community/cypher/acceptance/src/test/scala/org/neo4j/internal/cypher/acceptance/FunctionsAcceptanceTest.scala:232]: Could we add an additional test that goes red/green for the `&&`/`||` case I also commented on?

File: community/cypher/cypher/src/test/scala/org/neo4j/cypher/SemanticDeleteAcceptanceTest.scala (hunk 3 above)
Comment (Mats-SX) [inline community/cypher/cypher/src/test/scala/org/neo4j/cypher/SemanticDeleteAcceptanceTest.scala:70]: Agreed.
