### PR TITLE
Fix NPE after Recovery

### LINKED ISSUE #6335: NullPointerException in CommonAbstractStore#nextId
```
java.lang.NullPointerException: null
at org.neo4j.kernel.impl.store.CommonAbstractStore.nextId(CommonAbstractStore.java:419)
at org.neo4j.kernel.impl.api.store.DiskLayer.reserveNode(DiskLayer.java:678)
at org.neo4j.kernel.impl.api.store.CacheLayer.reserveNode(CacheLayer.java:457)
at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodeCreate(StateHandlingStatementOperations.java:323)
at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.nodeCreate(ConstraintEnforcingEntityOperations.java:368)
at org.neo4j.kernel.impl.api.LockingStatementOperations.nodeCreate(LockingStatementOperations.java:267)
at org.neo4j.kernel.impl.api.OperationsFacade.nodeCreate(OperationsFacade.java:851)
at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.createNode(GraphDatabaseFacade.java:187)
```

Seeing this for the first time. 

messages.log contains this:

```
2016-02-01 15:05:36.745+0000 ERROR [o.n.k.i.DiagnosticsManager] Failure while logging diagnostics for org.neo4j.kernel.info.DiagnosticsManager$ExtractedDiagnosticsProvider@53d91c95
java.lang.NullPointerException
at org.neo4j.kernel.impl.store.CommonAbstractStore.getNumberOfIdsInUse(CommonAbstractStore.java:701)
at org.neo4j.kernel.impl.store.CommonAbstractStore.logIdUsage(CommonAbstractStore.java:725)
at org.neo4j.kernel.impl.store.NeoStores.logIdUsage(NeoStores.java:648)
at org.neo4j.kernel.NeoStoreDataSource$Diagnostics$2.dump(NeoStoreDataSource.java:276)
at org.neo4j.kernel.NeoStoreDataSource$Diagnostics.dumpDiagnostics(NeoStoreDataSource.java:330)
at org.neo4j.kernel.NeoStoreDataSource$Diagnostics$2.dumpDiagnostics(NeoStoreDataSource.java:271)
at org.neo4j.kernel.info.DiagnosticsManager$ExtractedDiagnosticsProvider.dump(DiagnosticsManager.java:316)
at org.neo4j.kernel.info.DiagnosticsManager.dump(DiagnosticsManager.java:263)
at org.neo4j.kernel.info.DiagnosticsManager.dump(DiagnosticsManager.java:255)
at org.neo4j.kernel.info.DiagnosticsManager.appendProvider(DiagnosticsManager.java:249)
at org.neo4j.kernel.info.DiagnosticsManager.register(DiagnosticsManager.java:225)
at org.neo4j.kernel.info.DiagnosticsManager.registerAll(DiagnosticsManager.java:232)
at org.neo4j.kernel.NeoStoreDataSource.registerDiagnosticsWith(NeoStoreDataSource.java:1288)
at org.neo4j.kernel.impl.factory.EditionModule.doAfterRecoveryAndStartup(EditionModule.java:72)
at org.neo4j.kernel.ha.factory.HighlyAvailableEditionModule.doAfterRecoveryAndStartup(HighlyAvailableEditionModule.java:786)
at org.neo4j.kernel.ha.factory.HighlyAvailableEditionModule$15.doAfterRecoveryAndStartup(HighlyAvailableEditionModule.java:757)
at org.neo4j.kernel.ha.factory.HighlyAvailableEditionModule$15.masterIsAvailable(HighlyAvailableEditionModule.java:734)
at org.neo4j.kernel.ha.cluster.HighAvailabilityMemberStateMachine$StateMachineClusterEventListener$2.notify(HighAvailabilityMemberStateMachine.java:207)
at org.neo4j.kernel.ha.cluster.HighAvailabilityMemberStateMachine$StateMachineClusterEventListener$2.notify(HighAvailabilityMemberStateMachine.java:203)
at org.neo4j.helpers.Listeners.notifyListeners(Listeners.java:64)
at org.neo4j.kernel.ha.cluster.HighAvailabilityMemberStateMachine$StateMachineClusterEventListener.memberIsAvailable(HighAvailabilityMemberStateMachine.java:201)
at org.neo4j.cluster.member.paxos.PaxosClusterMemberEvents$AtomicBroadcastListenerImpl$1.notify(PaxosClusterMemberEvents.java:372)
at org.neo4j.cluster.member.paxos.PaxosClusterMemberEvents$AtomicBroadcastListenerImpl$1.notify(PaxosClusterMemberEvents.java:368)
at org.neo4j.helpers.Listeners.notifyListeners(Listeners.java:64)
at org.neo4j.cluster.member.paxos.PaxosClusterMemberEvents$AtomicBroadcastListenerImpl.receive(PaxosClusterMemberEvents.java:367)
at org.neo4j.cluster.protocol.atomicbroadcast.multipaxos.context.AtomicBroadcastContextImpl$1.notify(AtomicBroadcastContextImpl.java:77)
at org.neo4j.cluster.protocol.atomicbroadcast.multipaxos.context.AtomicBroadcastContextImpl$1.notify(AtomicBroadcastContextImpl.java:73)
at org.neo4j.helpers.Listeners$1.run(Listeners.java:87)
at org.neo4j.cluster.DelayedDirectExecutor.drain(DelayedDirectExecutor.java:93)
at org.neo4j.cluster.StateMachines$1.run(StateMachines.java:216)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:99)

```

But after that:

```
2016-02-01 15:05:36.822+0000 INFO  [o.n.k.h.HighAvailabilityLogger] Database available for write transactions
2016-02-01 15:05:36.822+0000 INFO  [o.n.k.h.f.HighlyAvailableFacadeFactory] Database is now ready

```

Also, :sysinfo show this:
err

### PR DESCRIPTION
**Pull request by spacecowboy**
Mark store as not OK after deleting its idGenerator, which will trigger
a rebuilding of the idGenerator once makeStoreOK is called.

The bug was introduced as part of the refactoring in 2.3: the test is green on 2.2.

Supercedes #7013 
Fixes #6335

### CODE REVIEW

**Comment by davidegrohmann** [comment]
@spacecowboy why the `2.2` label if the bug is in `2.3`?

File: community/kernel/src/main/java/org/neo4j/kernel/impl/store/CommonAbstractStore.java [hunk 1]
```diff
@@ -758,13 +766,16 @@ public final void visitStore( Visitor<CommonAbstractStore,RuntimeException> visi
...
+     *
+     * This also marks the store as not OK. A call to {@link #makeStoreOk()} is needed once recovery is complete.
      */
     final void deleteIdGenerator()
     {
         if ( idGenerator != null )
         {
             idGenerator.delete();
             idGenerator = null;
+            setStoreNotOk( null );
```
Comment (burqen) [inline community/kernel/src/main/java/org/neo4j/kernel/impl/store/CommonAbstractStore.java]: Could maybe use `new IllegalStateException( "IdGenerator is not initialized" )` as cause for store not being ok.

**Comment by spacecowboy** [comment]
@davidegrohmann good catch!

File: community/kernel/src/main/java/org/neo4j/kernel/impl/store/CommonAbstractStore.java (hunk 1 above)
Comment (spacecowboy) [inline community/kernel/src/main/java/org/neo4j/kernel/impl/store/CommonAbstractStore.java]: Good idea. Pushed a rebased version.

**Comment by tkroman** [comment]
@spacecowboy Will this make into the 3.0.2 release? We faced the issue with the 3.0.1 jar, but the 3.1.0-M01 looks like it doesn't have this problem, so I'd just like to make sure that this is consistently applied to all the (sub-)releases.

**Comment by chrisvest** [comment]
Yes, this will be in 3.0.2.
