### PR TITLE
Make buffer size configurable for `LOAD CSV`

### LINKED ISSUE #11687: Neo4j 3.3.5 LOAD CSV throw Neo.DatabaseError.Statement.ExecutionFailed
**Neo4j Version:** 3.3.5
**Operating System:** OS X 10.13.4
**Driver:**  Cypher

### Steps to reproduce
1. Access to own Neo4j browser.
2. Run the below cypher.
```
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM 'file:///test.csv' AS row CREATE (tx:TxOut { value: row.value, n: toInt(row.n), uuid: row.uuid, created_at: timestamp() }) SET tx.script_pubkey = row.script_pubkey, tx.updated_at = timestamp()
```
### Expect behavior
Import finishes without error.

### Actual behavior
That return the error.
```
Neo.DatabaseError.Statement.ExecutionFailed: Tried to read a field larger than buffer size 2097152. A common cause of this is that a field has an unterminated quote and so will try to seek until the next quote, which ever line it may be on. This should not happen if multi-line fields are disabled, given that the fields contains no new-line characters. This field started at <NEO4J-HOME>/import/test.csv:1
```

using file [here test.zip](https://github.com/neo4j/neo4j/files/1965963/test.zip)

### PR DESCRIPTION
**Pull request by pontusmelke**
If csv-file contains huge fields we will overflow the internal buffer and  throw an error without users able to do much. This PR adds a db configuration - `dbms.import.csv.buffer_size` - that allows the internal buffer to be increased.
Fixes #11687

changelog: Add db-setting: `dbms.import.csv.buffer_size` allowing for increasing the internal buffer in order to handle csv-files with huge fields.

### CODE REVIEW

**Review by fickludd — APPROVED** [review]
I think this solution is fine for a maintenance release, but in `3.5` I think we should rearchitect csv configuration to no be part of the operators, but rather live in `QueryState` or something. Or it should be handled directly by the csv loader so Cypher didn't need to know about this.

File: community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java [hunk 1]
```diff
@@ -337,7 +335,9 @@ private boolean fillBufferIfWeHaveExhaustedIt() throws IOException
                             dataLength + ". A common cause of this is that a field has an unterminated " +
                             "quote and so will try to seek until the next quote, which ever line it may be on." +
                             " This should not happen if multi-line fields are disabled, given that the fields contains " +
-                            "no new-line characters. This field started at " + sourceDescription() + ":" + lineNumber() );
+                            "no new-line characters. If you are running a `LOAD CSV query it may also be possible that " +
```
Comment (tinwelint) [inline community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java]: It's a bit of a hack to include this information in a component way below where LOAD CSV and that configuration option lives. It would be better to catch and repurpose this specific exception higher up, wouldn't it? You could introduce a specific subclass of IllegalStateException for this purpose, in the csv component and catch it in LOAD CSV land and add this piece of messaging to it.

**Review by tinwelint — CHANGES_REQUESTED** [review]

File: community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java (hunk 1 above)
Comment (pontusmelke) [reply community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java]: I agree but maybe we shouldn't change the error message at all in a maintenance release?

**Comment by pontusmelke** [comment]
Come to think of it I think the grown up thing to do is not to change the error message in a maintenance release. @tinwelint @fickludd wdyt?

**Comment by pontusmelke** [comment]
@tinwelint you are still in `requested changes` mode, did I miss something?

**Review by tinwelint — APPROVED** [review]

**Comment by PhaneendraNakkala** [comment]
Hi,
I'm facing this error on 3.1 neo4j community edition.
Is the setting `dbms.import.csv.buffer_size` available in 3.1.X?
Otherwise, Could you suggest me a solution to workaround on 3.1.X?

Cheers!
Phaneendra
