### PR TITLE
Fixes relationship cursor issue for dense node w/o relationships

### LINKED ISSUE #5691: IndexOutOfBoundsException on Relationship Iterator
I’m getting the following error upon switching from the community version 2.2.5 to the Enterprise evaluation version 2.3.0, is this perhaps a bug in the new version?

```
    try (Transaction tx = db.beginTx()) {
        Set<Node> nodesToClean = new HashSet<>();
        try (ResourceIterator<Node> nodes  = GenericQueries.getMatchesFromNodeLabel(GeneralLabels.FEATURE)) { // This just calls GraphDatabaseService.findNodes(label) on the db.
            while (nodes.hasNext()) {
                Node node = nodes.next();
                if (!node.getRelationships(Direction.OUTGOING, RelationshipTypes.HAS_INSTANCE).iterator().hasNext()) {  // <---- The error is thrown on this line.
                    nodesToClean.add(node);
                }
            }
        }
          //I’ve excluded the remaining code, as it is never reached. 
    }
```

Exception in thread "main" java.lang.IndexOutOfBoundsException
                at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.setOffset(MuninnPageCursor.java:419)
                at org.neo4j.kernel.impl.store.RelationshipGroupStore.readRecord(RelationshipGroupStore.java:143)
                at org.neo4j.kernel.impl.store.RelationshipGroupStore.forceGetRecord(RelationshipGroupStore.java:106)
                at org.neo4j.kernel.impl.api.store.StoreNodeRelationshipCursor.init(StoreNodeRelationshipCursor.java:89)
                at org.neo4j.kernel.impl.api.store.StoreAbstractNodeCursor.relationships(StoreAbstractNodeCursor.java:203)
                at org.neo4j.kernel.api.cursor.NodeItem$NodeItemHelper.getRelationships(NodeItem.java:81)
                at org.neo4j.kernel.impl.api.OperationsFacade.nodeGetRelationships(OperationsFacade.java:319)
                at org.neo4j.kernel.impl.core.NodeProxy$2.iterator(NodeProxy.java:201)
                at org.neo4j.kernel.impl.core.NodeProxy$2.iterator(NodeProxy.java:193)

### PR DESCRIPTION
**Pull request by tinwelint**
Nodes can be marked as dense when getting new relationships, although
never marked as sparse even after deleted below dense node threshold.
So there can be dense nodes w/o any relationships.

These was an assumption in StoreNodeRelationshipCursor that just because a
node was dense it had to have at least one relationship, and so it went
ahead and loaded a record regardless of the first relationship id, which
could be -1. This commit fixes that.

Closes #5691

### CODE REVIEW

File: community/kernel/src/test/java/org/neo4j/kernel/impl/api/store/StoreNodeRelationshipCursorTest.java [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+                mock( Consumer.class ),
+                NO_LOCK_SERVICE );
+
+        // WHEN
+        cursor.init( true, NO_NEXT_RELATIONSHIP.intValue(), 0, BOTH );
+
+        // THEN
+        verifyNoMoreInteractions( relationshipGroupStore );
+        assertFalse( cursor.next() );
+    }
```
Comment (davidegrohmann) [inline community/kernel/src/test/java/org/neo4j/kernel/impl/api/store/StoreNodeRelationshipCursorTest.java:72]: It is quite depressing that this is the only test we have for this cursor. Not your fault though.

**Comment by thobe** [comment]
Related: do we have tests that verify that once a dense node has lost all it's relationships, adding new relationships is possible?

**Comment by tinwelint** [comment]
@thobe added such a test as well.
