### PR TITLE
Cap optional matches in cardinality computation

### LINKED ISSUE #7407: Server endlessly stuck with 100% cpu usage
I was playing with some dummy graph and queries on neo4j 3.0.3 community. If I run queries below, the last query, which should delete the graph, runs endlessly with 100% cpu usage. It looks to me that neo4j is not able to plan the query.

I know that my queries are ugly and not for production use but neo4j should not crashed. I have tried the same queries on neo4j 2.3.2 and they worked.
- Neo4j version: 3.0.3 community
- Operating system: Ubuntu 14.04
- API/Driver: neo4j web console

**create a graph:**

```
create (n1: `node1` {oid: '1'})
create (n2: `node2` {oid: '2'})
create (n3: `node3` {oid: '3'}) 
create (n4: `node4` {oid: '4'}) 
create (n5: `node5` {oid: '5'}) 
create (n6: `node6` {oid: '6'}) 
create (n7: `node7` {oid: '7'}) 
create (n8: `users` {oid: '8'}) 
create (n9: `user` {oid: '9'})  
create (n1)-[r10:`HAS_CHILD` {oid: '10'}]->(n2) 
create (n1)-[r11:`HAS_CHILD` {oid: '11'}]->(n3) 
create (n2)-[r12:`HAS_CHILD` {oid: '12'}]->(n4) 
create (n2)-[r13:`HAS_CHILD` {oid: '13'}]->(n5) 
create (n3)-[r14:`HAS_CHILD` {oid: '14'}]->(n6)  
create (n3)-[r15:`HAS_CHILD` {oid: '15'}]->(n7) 
create (n8)-[r16:`SECURITY` {oid: '16'}]->(n3) 
create (n9)-[r17:`PART_OF` {oid: '17'}]->(n8)
```

**delete all nodes and relationships (this query crashes the server):**
`optional match(n0 { oid: '1'}) optional match(n1 { oid: '2'}) optional match(n2 { oid: '3'}) optional match(n3 { oid: '4'}) optional match(n4 { oid: '5'}) optional match(n5 { oid: '6'}) optional match(n6 { oid: '7'}) optional match(n7 { oid: '8'}) optional match(n8 { oid: '9'})  optional match( { oid : '1'})-[r0 { oid: '10'}]-( { oid : '2'}) optional match( { oid : '1'})-[r1 { oid: '11'}]-( { oid : '3'}) optional match( { oid : '2'})-[r2 { oid: '12'}]-( { oid : '4'}) optional match( { oid : '2'})-[r3 { oid: '13'}]-( { oid : '5'}) optional match( { oid : '3'})-[r4 { oid: '14'}]-( { oid : '6'}) optional match( { oid : '3'})-[r5 { oid: '15'}]-( { oid : '7'}) optional match( { oid : '8'})-[r6 { oid: '16'}]-( { oid : '3'}) optional match( { oid : '9'})-[r7 { oid: '17'}]-( { oid : '8'})  detach delete n0, n1, n2, n3, n4, n5, n6, n7, n8 delete r0, r1, r2, r3, r4, r5, r6, r7
`

### PR DESCRIPTION
**Pull request by pontusmelke**
The number of optional-match combinations to consider in the cardinality
estimation grows exponentially meaning that the plan time also grows
exponentially. Instead of considering all combinations - above a certain threshold
we only consider the combinations of the most costly optional matches.

fixes #7407
changelog: [cypher] Improve performance for queries with many `OPTIONAL MATCH`  - [#7407](#7407)

### CODE REVIEW

File: community/cypher/acceptance/src/test/scala/org/neo4j/internal/cypher/acceptance/DeleteAcceptanceTest.scala [hunk 1]
```diff
@@ -272,4 +277,48 @@ class DeleteAcceptanceTest extends ExecutionEngineFunSuite with QueryStatisticsT
     assertStats(result, nodesDeleted = 2, relationshipsDeleted = 2)
   }
 
+  //see https://github.com/neo4j/neo4j/issues/7407
+  test("should plan within reasonable time") {
+    updateWithBothPlannersAndCompatibilityMode("CREATE (n1: `node1` {oid: '1'})")
```
Comment (systay) [inline community/cypher/acceptance/src/test/scala/org/neo4j/internal/cypher/acceptance/DeleteAcceptanceTest.scala]: this should probably be a single query, and not be run through the `updateWithBothPlannersAndCompatibilityMode` thingie

Comment (pontusmelke) [inline community/cypher/acceptance/src/test/scala/org/neo4j/internal/cypher/acceptance/DeleteAcceptanceTest.scala]: What is the harm?

**Comment by henriknyman** [comment]
Maybe it would be nice to have a unit-test for the cap as well, but I will not stop you.
