### PR TITLE
Fixes a CSV trim issue with fields containing only whitespace

### LINKED ISSUE #11094: CSV import bug for 3.3.2+
I used NEO4J 3.3.1 on my mac to use neo4j-admin import shell to built graphs from CSV files and everything works fine. (followed by https://neo4j.com/docs/operations-manual/current/tools/import/)

I wanted to build the same database on my Ubuntu box(14.04) with NEO4J 3.3.2 so I scp all the CSV files from mac to ubuntu box and used the same shell to import CSV.

However, the importing data failed and neo4j complained the below ERRORS.
I tried to upgrade to 3.3.3 but it still failed in the same way. 
Finally I downgraded to 3.3.1 like what I have in Mac and it magically worked.

> WARNING Import failed. The store files in /home/mlo/neo4j-community-3.3.3/data/databases/tw_ml_v3.db are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually
> org.neo4j.unsafe.impl.batchimport.input.InputException: ERROR in input
>   data source: BufferedCharSeeker[source:/home/mlo/tw_ml_v3/merch_user_table.csv, position:2699377, line:9385]
>   in field: photo_id_number:string:15
>   for header: [id:ID(Merch_user), username:string, email:string, individual_name:string, store_url:string, is_banned:string, display_name:string, product_categories:string, date_last_active:string, tax_certificate:string, company_name:string, business_license:string, photo_id:string, warehouse_locations:string, photo_id_number:string, bd_rep:string]
>   raw field value: ??
>   original error: String index out of range: -283
> 	at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.deserializeNextFromSource(InputEntityDeserializer.java:178)
> 	at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.fetchNextOrNull(InputEntityDeserializer.java:77)
> 	at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.fetchNextOrNull(InputEntityDeserializer.java:41)
> 	at org.neo4j.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
> 	at org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
> 	at org.neo4j.unsafe.impl.batchimport.input.csv.ParallelInputEntityDeserializer.lambda$new$0(ParallelInputEntityDeserializer.java:106)
> 	at org.neo4j.unsafe.impl.batchimport.staging.TicketedProcessing.lambda$submit$1(TicketedProcessing.java:103)
> 	at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:237)
> 	Suppressed: org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic
> 		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.assertHealthy(DynamicTaskExecutor.java:146)
> 		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.submit(DynamicTaskExecutor.java:126)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.receive(ProcessorStep.java:78)
> 		at org.neo4j.unsafe.impl.batchimport.staging.Downstream.send(Downstream.java:56)
> 		at org.neo4j.unsafe.impl.batchimport.staging.SendDownstream.apply(SendDownstream.java:58)
> 		at org.neo4j.unsafe.impl.batchimport.staging.SendDownstream.apply(SendDownstream.java:26)
> 		at org.neo4j.concurrent.WorkSync.doSynchronizedWork(WorkSync.java:231)
> 		at org.neo4j.concurrent.WorkSync.tryDoWork(WorkSync.java:157)
> 		at org.neo4j.concurrent.WorkSync.applyAsync(WorkSync.java:122)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.sendDownstream(ProcessorStep.java:162)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.access$100(ProcessorStep.java:45)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$Sender.send(ProcessorStep.java:223)
> 		at org.neo4j.unsafe.impl.batchimport.PropertyEncoderStep.process(PropertyEncoderStep.java:137)
> 		at org.neo4j.unsafe.impl.batchimport.PropertyEncoderStep.process(PropertyEncoderStep.java:52)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:85)
> 		... 1 more
> 	[CIRCULAR REFERENCE:org.neo4j.unsafe.impl.batchimport.input.InputException: ERROR in input
>   data source: BufferedCharSeeker[source:/home/mlo/tw_ml_v3/merch_user_table.csv, position:2699377, line:9385]
>   in field: photo_id_number:string:15
>   for header: [id:ID(Merch_user), username:string, email:string, individual_name:string, store_url:string, is_banned:string, display_name:string, product_categories:string, date_last_active:string, tax_certificate:string, company_name:string, business_license:string, photo_id:string, warehouse_locations:string, photo_id_number:string, bd_rep:string]
>   raw field value: ??
>   original error: String index out of range: -283]
> 	[CIRCULAR REFERENCE:org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic]
> 	Suppressed: org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic
> 		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.assertHealthy(DynamicTaskExecutor.java:146)
> 		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.submit(DynamicTaskExecutor.java:126)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.receive(ProcessorStep.java:78)
> 		at org.neo4j.unsafe.impl.batchimport.staging.Downstream.send(Downstream.java:56)
> 		at org.neo4j.unsafe.impl.batchimport.staging.SendDownstream.apply(SendDownstream.java:58)
> 		at org.neo4j.unsafe.impl.batchimport.staging.SendDownstream.apply(SendDownstream.java:26)
> 		at org.neo4j.concurrent.WorkSync.doSynchronizedWork(WorkSync.java:231)
> 		at org.neo4j.concurrent.WorkSync.tryDoWork(WorkSync.java:157)
> 		at org.neo4j.concurrent.WorkSync.applyAsync(WorkSync.java:122)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.sendDownstream(ProcessorStep.java:162)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.access$100(ProcessorStep.java:45)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$Sender.send(ProcessorStep.java:223)
> 		at org.neo4j.unsafe.impl.batchimport.PropertyEncoderStep.process(PropertyEncoderStep.java:137)
> 		at org.neo4j.unsafe.impl.batchimport.PropertyEncoderStep.process(PropertyEncoderStep.java:52)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:85)
> 		... 1 more
> 	[CIRCULAR REFERENCE:org.neo4j.unsafe.impl.batchimport.input.InputException: ERROR in input
>   data source: BufferedCharSeeker[source:/home/mlo/tw_ml_v3/merch_user_table.csv, position:2699377, line:9385]
>   in field: photo_id_number:string:15
>   for header: [id:ID(Merch_user), username:string, email:string, individual_name:string, store_url:string, is_banned:string, display_name:string, product_categories:string, date_last_active:string, tax_certificate:string, company_name:string, business_license:string, photo_id:string, warehouse_locations:string, photo_id_number:string, bd_rep:string]
>   raw field value: ??
>   original error: String index out of range: -283]
> 	[CIRCULAR REFERENCE:org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic]
> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -283
> 	at java.lang.String.<init>(String.java:196)
> 	at org.neo4j.csv.reader.Extractors$StringExtractor.extract0(Extractors.java:329)
> 	at org.neo4j.csv.reader.Extractors$AbstractSingleValueExtractor.extract(Extractors.java:290)
> 	at org.neo4j.csv.reader.BufferedCharSeeker.tryExtract(BufferedCharSeeker.java:283)
> 	at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.deserializeNextFromSource(InputEntityDeserializer.java:138)
> 	... 7 more
> unexpected error: ERROR in input
>   data source: BufferedCharSeeker[source:/home/mlo/tw_ml_v3/merch_user_table.csv, position:2699377, line:9385]
>   in field: photo_id_number:string:15
>   for header: [id:ID(Merch_user), username:string, email:string, individual_name:string, store_url:string, is_banned:string, display_name:string, product_categories:string, date_last_active:string, tax_certificate:string, company_name:string, business_license:string, photo_id:string, warehouse_locations:string, photo_id_number:string, bd_rep:string]
>   raw field value: ??
>   original error: String index out of range: -283

### LINKED ISSUE #11218: neo4j-admin import fails to parse csv
- Neo4j version: 3.3.3-1 installed through yum
- Operating system: centos 7
- API/Driver: neo4j-admin import

I'm loading a large (1M+ records with 40 fields) csv file with the following (simplified) command:
neo4j-admin import \
    --nodes:Organization /path/to/organizations.csv \
    --multiline-fields=true \
    --ignore-duplicate-nodes=true \
    --ignore-missing-nodes=true \
    --array-delimiter ";"

And since a couple of weeks it regularly fails with: 
```
WARNING Import failed. The store files in /path/to/graph.db are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually
unexpected error: ERROR in input
  data source: BufferedCharSeeker[source:/path/to/organizations.csv, position:301989889, line:1100684]
  in field: abbreviationFr:string:6
  for header: [vat:ID(Organization), ... , abbreviationFr:string, ...]
  raw field value: ??
  original error: String index out of range: -1
```

This error occurs deterministically in the sense that once it happens it will consistently happen with the same input. However, it may just go away after simply reordering the fields, removing a line or sometimes even a cell. I have tried to isolate the issue by only taking the lines around the line number mentioned in the error as the input but I havent been able to reproduce the error in this way.

The csv file itself should be valid csv since it was generated from Spark.

Any idea what could be wrong? Did you make any changes to the import in the recent versions? Anything I can do to pinpoint the issue?

Thanks in advance,

Niek.

### PR DESCRIPTION
**Pull request by tinwelint**
This could result in StringIndexOutOfBounds with negative values
for some fields containing nothing but whitespace characters.

Fixes #11094
Fixes #11218

### CODE REVIEW

**Comment by tinwelint** [comment]
The failing test has failed lots of times before, so I can't see it being caused by these changes.

File: community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java [hunk 1]
```diff
@@ -194,15 +194,15 @@ else if ( eof )
...
     private boolean setMark( Mark mark, int endOffset, int skippedChars, int ch, boolean isQuoted )
     {
-        int pos = (trim ? rtrim( bufferPos ) : bufferPos) - endOffset - skippedChars;
+        int pos = (trim ? rtrim() : bufferPos) - endOffset - skippedChars;
         mark.set( seekStartPos, pos, ch, isQuoted );
         return true;
     }
 
-    private int rtrim( int start )
+    private int rtrim()
```
Comment (ragadeeshu) [inline community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java]: This whole method could use some more comments. There are some, but for the most part, especially with the new addition, it is black magic.

**Review by ragadeeshu — CHANGES_REQUESTED** [review]

**Comment by tinwelint** [comment]
Added javadoc now to that method, please take a look

File: community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java [hunk 2]
```diff
@@ -194,15 +194,21 @@ else if ( eof )
...
+     * Although it cannot scan further back than the start of this field is, i.e. {@link #seekStartPos}.
+     *
+     * @return the right index of the value to pass into {@link Mark}. This is only called if {@link Configuration#trimStrings()} is {@code true}.
+     */
+    private int rtrim()
     {
-        int index = start;
-        while ( isWhitespace( buffer[index - 1 /*bufferPos has advanced*/ - 1 /*don't check the last read char (delim or EOF)*/] ) )
+        int index = bufferPos;
+        while ( index - 1 > seekStartPos && isWhitespace( buffer[index - 1 /*bufferPos has advanced*/ - 1 /*don't check the last read char (delim or EOF)*/] ) )
```
Comment (andreikoval) [inline community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java:209]: What about other space characters, like non-breaking space, tabs, etc?

**Review by ragadeeshu — APPROVED** [review]

File: community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java (hunk 2 above)
Comment (tinwelint) [reply community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java:209]: Yeah, perhaps use Character#isWhitespace() instead. This (BufferedCharSeeker#isWhitespace()) method was introduced along with the previous fix which was released in Jan or so... so I'd say changing this should be OK and more of a fix than changing behaviour.

Comment (tinwelint) [reply community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java:209]: @andreikoval How about now? Oh wait, doesn't work

Comment (andreikoval) [reply community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java:209]: Yep, I guess that is because `Character.isWhitespace()` includes line breaking spaces as well.

Comment (tinwelint) [reply community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java:209]: It was a test issue, really. Have a look now
