### PR TITLE
Fixes an issue where log rotation would cut transaction in half

### LINKED ISSUE #7204: Unknown command/entry type exception at shutdown
I'm using Neo4j in embedded mode and am trying to upgrade to version 3.
After populating the database, I get weird exceptions when invoking the GraphDatabaseService#shutdown method. I did some research but couldn't find anything relevant to my issue.

Also, it gets stranger when I try to reduce the data set to reproduce the exception with a more reasonable runtime, it gets through the load process and succeeds. Therefore I don't really have a way to reproduce that apart from running a long load of several hours.

In hope to receive some hints, I'll paste 2 different logs which have been executed on 2 different machines. (Note that the exception message is different).

**Neo4j Version:** 3.0.1
**Java Version:** 1.8.0_91
**Maven Version:** 3.0.5
**Operating System:** Ubuntu 14.04

**First log:**

> [WARNING] 
> java.lang.reflect.InvocationTargetException
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@4a7fe705' failed to stop. Please see attached cause exception.
>   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:466)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
>   at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:119)
>   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:458)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
>   at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:191)
>   at org.neo4j.kernel.impl.factory.ClassicCoreSPI.shutdown(ClassicCoreSPI.java:158)
>   at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.shutdown(GraphDatabaseFacade.java:324)
>   at io.scigraph.owlapi.loader.BatchOwlLoader$PostpostprocessorProvider.shutdown(BatchOwlLoader.java:190)
>   at io.scigraph.owlapi.loader.BatchOwlLoader.loadOntology(BatchOwlLoader.java:158)
>   at io.scigraph.owlapi.loader.BatchOwlLoader.load(BatchOwlLoader.java:203)
>   at io.scigraph.owlapi.loader.BatchOwlLoader.main(BatchOwlLoader.java:233)
>   ... 6 more
>   Suppressed: org.neo4j.kernel.lifecycle.LifecycleException: Failed to transition component 'org.neo4j.kernel.impl.pagecache.PageCacheLifecycle@4bdf7742' from STOPPED to SHUTTING_DOWN. Please see attached cause exception
>       at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:497)
>       at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:206)
>       ... 12 more
>   Caused by: java.lang.IllegalStateException: Cannot close the PageCache while files are still mapped:
>   neostore.counts.db.b (1 mapping)
>   neostore (1 mapping)
>   neostore.relationshipgroupstore.db (1 mapping)
>   neostore.schemastore.db (1 mapping)
>   neostore.labeltokenstore.db (1 mapping)
>   neostore.labeltokenstore.db.names (1 mapping)
>   neostore.relationshiptypestore.db (1 mapping)
>   neostore.relationshiptypestore.db.names (1 mapping)
>   neostore.relationshipstore.db (1 mapping)
>   neostore.propertystore.db (1 mapping)
>   neostore.propertystore.db.arrays (1 mapping)
>   neostore.propertystore.db.strings (1 mapping)
>   neostore.propertystore.db.index (1 mapping)
>   neostore.propertystore.db.index.keys (1 mapping)
>   neostore.nodestore.db (1 mapping)
>   neostore.nodestore.db.labels (1 mapping)
>       at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.close(MuninnPageCache.java:539)
>       at org.neo4j.kernel.impl.pagecache.PageCacheLifecycle.shutdown(PageCacheLifecycle.java:42)
>       at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:489)
>       ... 13 more
> Caused by: java.lang.RuntimeException: java.io.IOException: Unknown command type[-123] near LogPosition{logVersion=30, byteOffset=24}
>   at org.neo4j.kernel.impl.transaction.log.pruning.EntryTimespanThreshold.reached(EntryTimespanThreshold.java:63)
>   at org.neo4j.kernel.impl.transaction.log.pruning.ThresholdBasedPruneStrategy.prune(ThresholdBasedPruneStrategy.java:68)
>   at org.neo4j.kernel.impl.transaction.log.pruning.LogPruningImpl.pruneLogs(LogPruningImpl.java:54)
>   at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:224)
>   at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.forceCheckPoint(CheckPointerImpl.java:114)
>   at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:883)
>   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:458)
>   ... 19 more
> Caused by: java.io.IOException: Unknown command type[-123] near LogPosition{logVersion=30, byteOffset=24}
>   at org.neo4j.kernel.impl.transaction.command.BaseCommandReader.unknownCommandType(BaseCommandReader.java:76)
>   at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV2_0.read(PhysicalLogCommandReaderV2_0.java:76)
>   at org.neo4j.kernel.impl.transaction.command.BaseCommandReader.read(BaseCommandReader.java:53)
>   at org.neo4j.kernel.impl.transaction.command.BaseCommandReader.read(BaseCommandReader.java:34)
>   at org.neo4j.kernel.impl.transaction.log.entry.LogEntryParsersV2_0$4.parse(LogEntryParsersV2_0.java:135)
>   at org.neo4j.kernel.impl.transaction.log.entry.LogEntryParsersV2_0$4.parse(LogEntryParsersV2_0.java:127)
>   at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:98)
>   at org.neo4j.kernel.NeoStoreDataSource$2.getTimestampForVersion(NeoStoreDataSource.java:611)
>   at org.neo4j.kernel.impl.transaction.log.PhysicalLogFileInformation.getFirstStartRecordTimestamp(PhysicalLogFileInformation.java:98)
>   at org.neo4j.kernel.impl.transaction.log.pruning.EntryTimespanThreshold.reached(EntryTimespanThreshold.java:54)
>   ... 25 more

**Second log:**

> [WARNING] 
> java.lang.reflect.InvocationTargetException
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@10344bf0' failed to stop. Please see attached cause exception.
>   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:466)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
>   at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:119)
>   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:458)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
>   at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:191)
>   at org.neo4j.kernel.impl.factory.ClassicCoreSPI.shutdown(ClassicCoreSPI.java:158)
>   at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.shutdown(GraphDatabaseFacade.java:324)
>   at io.scigraph.owlapi.loader.BatchOwlLoader$PostpostprocessorProvider.shutdown(BatchOwlLoader.java:190)
>   at io.scigraph.owlapi.loader.BatchOwlLoader.loadOntology(BatchOwlLoader.java:158)
>   at io.scigraph.owlapi.loader.BatchOwlLoader.load(BatchOwlLoader.java:203)
>   at io.scigraph.owlapi.loader.BatchOwlLoader.main(BatchOwlLoader.java:233)
>   ... 6 more
>   Suppressed: org.neo4j.kernel.lifecycle.LifecycleException: Failed to transition component 'org.neo4j.kernel.impl.pagecache.PageCacheLifecycle@5af2ff6d' from STOPPED to SHUTTING_DOWN. Please see attached cause exception
>       at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:497)
>       at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:206)
>       ... 12 more
>   Caused by: java.lang.IllegalStateException: Cannot close the PageCache while files are still mapped:
>   neostore.counts.db.a (1 mapping)
>   neostore (1 mapping)
>   neostore.relationshipgroupstore.db (1 mapping)
>   neostore.schemastore.db (1 mapping)
>   neostore.labeltokenstore.db (1 mapping)
>   neostore.labeltokenstore.db.names (1 mapping)
>   neostore.relationshiptypestore.db (1 mapping)
>   neostore.relationshiptypestore.db.names (1 mapping)
>   neostore.relationshipstore.db (1 mapping)
>   neostore.propertystore.db (1 mapping)
>   neostore.propertystore.db.arrays (1 mapping)
>   neostore.propertystore.db.strings (1 mapping)
>   neostore.propertystore.db.index (1 mapping)
>   neostore.propertystore.db.index.keys (1 mapping)
>   neostore.nodestore.db (1 mapping)
>   neostore.nodestore.db.labels (1 mapping)
>       at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.close(MuninnPageCache.java:539)
>       at org.neo4j.kernel.impl.pagecache.PageCacheLifecycle.shutdown(PageCacheLifecycle.java:42)
>       at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:489)
>       ... 13 more
> Caused by: java.lang.IllegalArgumentException: Unknown entry type 105 for version 0. At position LogPosition{logVersion=17, byteOffset=16} and entry version V2_0
>   at org.neo4j.kernel.impl.transaction.log.entry.LogEntryVersion.entryParser(LogEntryVersion.java:126)
>   at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:84)
>   at org.neo4j.kernel.NeoStoreDataSource$2.getTimestampForVersion(NeoStoreDataSource.java:611)
>   at org.neo4j.kernel.impl.transaction.log.PhysicalLogFileInformation.getFirstStartRecordTimestamp(PhysicalLogFileInformation.java:98)
>   at org.neo4j.kernel.impl.transaction.log.pruning.EntryTimespanThreshold.reached(EntryTimespanThreshold.java:54)
>   at org.neo4j.kernel.impl.transaction.log.pruning.ThresholdBasedPruneStrategy.prune(ThresholdBasedPruneStrategy.java:68)
>   at org.neo4j.kernel.impl.transaction.log.pruning.LogPruningImpl.pruneLogs(LogPruningImpl.java:54)
>   at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:224)
>   at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.forceCheckPoint(CheckPointerImpl.java:114)
>   at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:883)
>   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:458)
>   ... 19 more

### PR DESCRIPTION
**Pull request by tinwelint**
The rotation done in PhysicalLogFile only flushed the channel,
i.e. bytes already written to it. It didn't tell the writer to
empty its buffer into the channel first. This could sometimes
result in rotation happening in the middle of a transaction.
All the bytes would be there, just split across files and be
more difficult to read later on if not using proper log version
bridging and would eventually cause problems when first part of
split transaction would be pruned.

This change will have transactions be fully written in the log
they started being written to before rotation happens, without
introducing any performance penalty of appending, forcing
or rotation.

Included in this PR is also a fix for having recovery use LogicalTransactionStore
so that it's able to read split transactions, this also simplifies and reduces
the recovery code since lots of special code for reading log files is
now deleted in favour of existing ways of doing that.

changelog: Fixes [#7204](https://github.com/neo4j/neo4j/issues/7204) an issue where log rotation sometimes would cut a transaction in half making it problematic for recovery to read such transactions. Transactions are now never split into multiple log files. Any db experiencing this issue can now also start that db with this fix included due to improved log reading abilities.

### CODE REVIEW

**Comment by tinwelint** [comment]
Please null-merge this or ping me about merging forward to 3.0 as it's slightly tricky and I've done it in a branch already. Thanks

**Comment by tinwelint** [comment]
I've been running recovery-robustness on this branch for quite a while and it has been successful as well

File: community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/LogicalTransactionStore.java [hunk 1]
```diff
@@ -23,25 +23,42 @@
...
      * @throws IOException if there was an I/O related error looking for the start transaction.
      */
-    IOCursor<CommittedTransactionRepresentation> getTransactions( long transactionIdToStartFrom )
+    TransactionCursor getTransactions( long transactionIdToStartFrom )
+            throws NoSuchTransactionException, IOException;
+
+    /**
+     * Acquires a {@link TransactionCursor cursor} which will provide {@link CommittedTransactionRepresentation}
+     * instances for committed transactions, starting from the specified {@link LogPosition}.
+     * This is useful for placing a cursor at a position refered to by a {@link CheckPoint}.
```
Comment (MishaDemianenko) [inline community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/LogicalTransactionStore.java]: referred

File: community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/LogicalTransactionStore.java [hunk 2]
```diff
@@ -23,25 +23,42 @@
...
+     * Transactions will be returned from the cursor in transaction-id-sequential order.
+     *
+     * @param position {@link LogPosition} of the first transaction that the cursor will return.
+     * @return an {@link TransactionCursor} capable of returning {@link CommittedTransactionRepresentation} instances
+     * for committed transactions, starting from the specified {@code transactionIdToStartFrom}.
```
Comment (MishaDemianenko) [inline community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/LogicalTransactionStore.java]: transactionIdToStartFrom is no longer here :)

File: community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/LogicalTransactionStore.java [hunk 3]
```diff
@@ -23,25 +23,42 @@
...
+     * @throws NoSuchTransactionException if the requested transaction hasn't been committed,
+     * or if the transaction has been committed, but information about it is no longer available for some reason.
+     * @throws IOException if there was an I/O related error looking for the start transaction.
+     */
+    TransactionCursor getTransactions( LogPosition position )
```
Comment (MishaDemianenko) [inline community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/LogicalTransactionStore.java:61]: NoSuchTransactionException is a subclass of IOException and declaration of it is redundant

File: community/kernel/src/main/java/org/neo4j/kernel/NeoStoreDataSource.java [hunk 4]
```diff
@@ -1030,31 +1017,33 @@ private void buildRecovery( final FileSystemAbstraction fileSystemAbstraction, C
...
-        life.add( new LifecycleAdapter()
+        monitors.addMonitorListener( new Recovery.Monitor()
         {
             @Override
-            public void init() throws Throwable
+            public void recoveryCompleted( int numberOfRecoveredTransactions )
             {
-                startupStatistics.setNumberOfRecoveredTransactions( recoveredCount.get() );
-                recoveredCount.set( 0 );
+                startupStatistics.setNumberOfRecoveredTransactions( numberOfRecoveredTransactions );
```
Comment (MishaDemianenko) [inline community/kernel/src/main/java/org/neo4j/kernel/NeoStoreDataSource.java:1033]: This is already great improvement to what it was before, but would it be much more easier pass startupStatistic inside recovery and update number of recovered transactions directly after migration without using monitors?

File: community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/PhysicalLogFile.java [hunk 5]
```diff
@@ -149,7 +149,13 @@ private PhysicalLogVersionedStoreChannel rotate( LogVersionedStoreChannel curren
...
          */
         long newLogVersion = logVersionRepository.incrementAndGetVersion();
-        currentLog.flush();
+        /*
+         * Rotation can happen at any point, although not concurrently with an append,
+         * although an append may have (most likely actually) left at least some bytes left
+         * in the buffer for future flushing. Flushing that buffer now makes the last appended
+         * transaction complete in the log we're rotating away. Awesome.
+         */
+        writer.emptyBufferIntoChannelAndClearIt().flush();
```
Comment (MishaDemianenko) [inline community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/PhysicalLogFile.java:158]: would it make more sense if we change LogVersionedStoreChannel to perform buffer flush first as part of channel flush? That will prevent case when we will forget to call `emptyBufferIntoChannelAndClearIt`

File: community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/PhysicalLogicalTransactionStore.java [hunk 6]
```diff
@@ -49,7 +49,13 @@ public PhysicalLogicalTransactionStore( LogFile logFile, TransactionMetadataCach
 
 
     @Override
-    public IOCursor<CommittedTransactionRepresentation> getTransactions( final long transactionIdToStartFrom )
+    public TransactionCursor getTransactions( LogPosition position ) throws NoSuchTransactionException, IOException
```
Comment (MishaDemianenko) [inline community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/PhysicalLogicalTransactionStore.java]: NoSuchTransactionException is redundant here

File: community/kernel/src/main/java/org/neo4j/kernel/recovery/DefaultRecoverySPI.java [hunk 7]
```diff
@@ -20,54 +20,62 @@
...
     private final RecoveryIndexingUpdatesValidator indexUpdatesValidator;
+    private final TransactionIdStore transactionIdStore;
+    private final LogicalTransactionStore logicalTransactionStore;
+    private final TransactionRepresentationStoreApplier storeApplier;
 
     public DefaultRecoverySPI( RecoveryLabelScanWriterProvider labelScanWriters,
             RecoveryLegacyIndexApplierLookup legacyIndexApplierLookup,
             StoreFlusher storeFlusher, NeoStores neoStores,
-            Visitor<LogVersionedStoreChannel,IOException> logFileRecoverer,
             PhysicalLogFiles logFiles, FileSystemAbstraction fileSystemAbstraction,
```
Comment (MishaDemianenko) [inline community/kernel/src/main/java/org/neo4j/kernel/recovery/DefaultRecoverySPI.java]: logFiles and fileSystemAbstraction is no longer used and should be removed

File: community/kernel/src/main/java/org/neo4j/kernel/recovery/DefaultRecoverySPI.java [hunk 8]
```diff
@@ -88,61 +96,64 @@ public void forceEverything()
...
+    public void allTransactionsRecovered( CommittedTransactionRepresentation lastRecoveredTransaction,
+            LogPosition positionAfterLastRecoveredTransaction ) throws Exception
+    {
+        transactionIdStore.setLastCommittedAndClosedTransactionId(
+                lastRecoveredTransaction.getCommitEntry().getTxId(),
+                LogEntryStart.checksum( lastRecoveredTransaction.getStartEntry() ),
+                lastRecoveredTransaction.getCommitEntry().getTimeWritten(),
+                positionAfterLastRecoveredTransaction.getByteOffset(),
+                positionAfterLastRecoveredTransaction.getLogVersion() );
+        // TODO: Also truncate last log after last known position
```
Comment (MishaDemianenko) [inline community/kernel/src/main/java/org/neo4j/kernel/recovery/DefaultRecoverySPI.java]: TODO broke through :)

File: community/kernel/src/main/java/org/neo4j/kernel/recovery/DefaultRecoverySPI.java [hunk 9]
```diff
@@ -20,54 +20,62 @@
...
+import org.neo4j.kernel.impl.transaction.log.TransactionCursor;
+import org.neo4j.kernel.impl.transaction.log.TransactionIdStore;
+import org.neo4j.kernel.impl.transaction.log.entry.LogEntryStart;
 import org.neo4j.kernel.impl.transaction.log.rotation.StoreFlusher;
 
-import static org.neo4j.kernel.impl.transaction.log.PhysicalLogFile.tryOpenForVersion;
+import static org.neo4j.kernel.impl.api.TransactionApplicationMode.RECOVERY;
 
-public class DefaultRecoverySPI implements Recovery.SPI
+public class DefaultRecoverySPI implements Recovery.SPI, Visitor<CommittedTransactionRepresentation,Exception>
```
Comment (MishaDemianenko) [inline community/kernel/src/main/java/org/neo4j/kernel/recovery/DefaultRecoverySPI.java]: I would say that current design where recovery spi is also a visitor i find  more overloaded then previous version where those a 2 different things

File: community/kernel/src/main/java/org/neo4j/kernel/recovery/DefaultRecoverySPI.java [hunk 10]
```diff
@@ -88,61 +96,64 @@ public void forceEverything()
...
-            {
-                throw new UnsupportedOperationException();
-            }
-        };
+        // Calling this method means that recovery is required, tell storage engine about it
+        // This method will be called before recovery actually starts and so will ensure that
+        // each store is aware that recovery will be performed. At this point all the stores have
+        // already started btw.
+        // Go and read more at {@link CommonAbstractStore#deleteIdGenerator()}
+        neoStores.deleteIdGenerators();
```
Comment (MishaDemianenko) [inline community/kernel/src/main/java/org/neo4j/kernel/recovery/DefaultRecoverySPI.java:115]: this looks strange now....critical call in a getter...

File: community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java [hunk 11]
```diff
@@ -0,0 +1,276 @@
...
+import static java.util.concurrent.TimeUnit.MILLISECONDS;
+import static java.util.concurrent.TimeUnit.SECONDS;
+import static java.util.concurrent.locks.LockSupport.parkNanos;
+
+import static org.neo4j.io.ByteUnit.mebiBytes;
+import static org.neo4j.kernel.impl.transaction.log.entry.LogHeader.LOG_HEADER_SIZE;
+import static org.neo4j.kernel.impl.transaction.tracing.LogAppendEvent.NULL;
+import static org.neo4j.kernel.impl.util.IdOrderingQueue.BYPASS;
+
+public class TransactionLogAppendAndRotateStressIT
```
Comment (MishaDemianenko) [inline community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java]: should we create separate stress test build for it instead?

File: community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java [hunk 12]
```diff
@@ -0,0 +1,276 @@
...
+                {
+                    while ( !end.get() )
+                    {
+                        try
+                        {
+                            appender.append( sillyTransaction( 1_000 ), NULL );
+                        }
+                        catch ( Exception e )
+                        {
+                            e.printStackTrace( System.out );
```
Comment (MishaDemianenko) [inline community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java]: SuppressOutput rule instead?

File: community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java [hunk 13]
```diff
@@ -0,0 +1,276 @@
...
+            LogEntry entry = null;
+            int state = 0;
+            int transactions = 0;
+            while ( (entry = entryReader.readLogEntry( reader )) != null )
+            {
+                switch ( state )
+                {
+                case 0: // Expects start entry
+                    assertTrue( entry instanceof LogEntryStart );
+                    state = 1;
```
Comment (MishaDemianenko) [inline community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java]: what if we will do state++ here

File: community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java [hunk 14]
```diff
@@ -0,0 +1,276 @@
...
+                    break;
+                case 1: // Expects command/commit entry
+                    assertTrue( entry instanceof LogEntryCommand || entry instanceof LogEntryCommit );
+                    if ( entry instanceof LogEntryCommit )
+                    {
+                        state = 0;
```
Comment (MishaDemianenko) [inline community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java]: and state -- here

File: community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java [hunk 15]
```diff
@@ -0,0 +1,276 @@
...
+                        transactions++;
+                    }
+                    break;
+                default: throw new IllegalArgumentException();
+                }
+            }
+            assertEquals( 0, state );
```
Comment (MishaDemianenko) [inline community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java]: and final state should be 0 here as result :) ?

File: community/kernel/src/test/java/org/neo4j/kernel/RecoveryTest.java [hunk 16]
```diff
@@ -275,6 +275,10 @@ public void recoveryRequired()
         }
     }
 
+    // TODO: Test about truncate file
```
Comment (MishaDemianenko) [inline community/kernel/src/test/java/org/neo4j/kernel/RecoveryTest.java]: TODO's

File: community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/PhysicalTransactionCursor.java [hunk 17]
```diff
@@ -33,18 +33,18 @@
 import org.neo4j.kernel.impl.transaction.log.entry.LogEntryStart;
 
 public class PhysicalTransactionCursor<T extends ReadableLogChannel>
-        implements IOCursor<CommittedTransactionRepresentation>
+        implements TransactionCursor
```
Comment (MishaDemianenko) [inline community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/PhysicalTransactionCursor.java:36]: there is `protected List<Command> commandList()` which can be inlined now

**Comment by MishaDemianenko** [comment]
@tinwelint review round completed, couple of comments.
It looks great and much more simple then it was before!

File: community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/LogicalTransactionStore.java (hunk 3 above)
Comment (tinwelint) [reply community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/LogicalTransactionStore.java:61]: Was following convention, perhaps it's declared to be explicit... just like IOException, ReadPastEndException (in log entry reading), which is very nice to advertise

File: community/kernel/src/main/java/org/neo4j/kernel/NeoStoreDataSource.java (hunk 4 above)
Comment (tinwelint) [reply community/kernel/src/main/java/org/neo4j/kernel/NeoStoreDataSource.java:1033]: Dunno, it's nice in a way to keep recovery as generic as possible. Don't think we should change more than required in a maint version this far back.

File: community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/PhysicalLogFile.java (hunk 5 above)
Comment (tinwelint) [reply community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/PhysicalLogFile.java:158]: Yeah, that's a good alternative to this actually, will try it out

File: community/kernel/src/main/java/org/neo4j/kernel/recovery/DefaultRecoverySPI.java (hunk 10 above)
Comment (tinwelint) [reply community/kernel/src/main/java/org/neo4j/kernel/recovery/DefaultRecoverySPI.java:115]: I wanted to remove the constraint that the `recoveryRequired()` needed to be called before `getRecoveryVisitor()`. Renaming `getRecoveryVisitor()` to `startRecovery()` feels better, wdyt?

File: community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java (hunk 11 above)
Comment (tinwelint) [reply community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java]: It runs in 2 seconds or so, perhaps it could simply be an IT?

File: community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java (hunk 12 above)
Comment (tinwelint) [inline community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java]: I think we can remove this printStackTrace since a test failure will show the exception anyway.

File: community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/LogicalTransactionStore.java (hunk 3 above)
Comment (MishaDemianenko) [reply community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/LogicalTransactionStore.java:61]: that's maybe true except some of the implementations do that, some not probably depending who opens them last )

File: community/kernel/src/main/java/org/neo4j/kernel/NeoStoreDataSource.java (hunk 4 above)
Comment (MishaDemianenko) [reply community/kernel/src/main/java/org/neo4j/kernel/NeoStoreDataSource.java:1033]: ok

File: community/kernel/src/main/java/org/neo4j/kernel/recovery/DefaultRecoverySPI.java (hunk 10 above)
Comment (MishaDemianenko) [reply community/kernel/src/main/java/org/neo4j/kernel/recovery/DefaultRecoverySPI.java:115]: yes sounds much better

File: community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java (hunk 12 above)
Comment (tinwelint) [reply community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java]: That wouldn't help because any exception fails the test and so SuppressOutput would print it anyway. Having this printing should be fine since it won't print on green test and you want to have more information when failing.

File: community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java (hunk 11 above)
Comment (MishaDemianenko) [reply community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java]: ok then lets to it simple IT

File: community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java (hunk 13 above)
Comment (tinwelint) [reply community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java]: It can be simplified with a boolean instead, since it's either 0 or 1

File: community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java (hunk 12 above)
Comment (MishaDemianenko) [reply community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java]: ok fair

File: community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java (hunk 13 above)
Comment (MishaDemianenko) [reply community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/log/TransactionLogAppendAndRotateStressIT.java]: that's true but with counter we will check that number of entry start is the same as number of commits

File: community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/LogicalTransactionStore.java (hunk 3 above)
Comment (tinwelint) [reply community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/LogicalTransactionStore.java:61]: Right, we can remove those from implementors as we see them (there was one mentioned below which is now fixed).

File: community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/PhysicalTransactionCursor.java (hunk 17 above)
Comment (tinwelint) [reply community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/PhysicalTransactionCursor.java:36]: fixed

File: community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/PhysicalLogFile.java (hunk 5 above)
Comment (tinwelint) [reply community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/PhysicalLogFile.java:158]: Hmm, actually this turns out to be two separate things. Flushing can only be done by calling `emptyBufferIntoChannelAndClearIt()` unless you have a direct reference to the underlying channel, which is what rotation code in PhysicalLogFile did wrong.

**Comment by tinwelint** [comment]
@MishaDemianenko added a couple of more commits addressing the comments

File: community/kernel/src/test/java/org/neo4j/kernel/RecoveryTest.java [hunk 18]
```diff
@@ -275,6 +275,154 @@ public void recoveryRequired()
...
+                writer.writeStartEntry( 0, 1, 5l, 4l, new byte[0] );
+
+                return true;
+            }
+        } );
+
+        LifeSupport life = new LifeSupport();
+        Recovery.Monitor monitor = mock( Recovery.Monitor.class );
+        final AtomicBoolean recoveryRequired = new AtomicBoolean();
+        try
```
Comment (MishaDemianenko) [inline community/kernel/src/test/java/org/neo4j/kernel/RecoveryTest.java]: this whole try catch block duplicates and should be extracted

**Comment by MishaDemianenko** [comment]
@tinwelint small comment about test, otherwise ready to merge
