### PR TITLE
Remove type expectation from IN

### LINKED ISSUE #5921: Weird behaviour/ errors in 2.3.1    (worked fine in 2.2.2)
We have some weird behaviour with collections :(

neo4j-sh (?)$ export selection=[30688,27682]```

This query runs fine:

neo4j-sh (?)$ with  {selection} as collection

> match p=(n)-[_..3]-(m) 
> // no paths that pass through other nodes in the selection
> where 
>     id(n) in collection
>     and NOT (n IN TAIL(nodes(p)))
> with id(m) as idm,id(n) as idn,length(p) as lp, count(_) as count,collection order by idm,idn,lp asc
> with idm,idn,collect([lp,count]) as c1,collection
>    where NOT idm IN collection
> // weighing of paths.. each hop further a factor 10 less
> with idm,idn, c1,reduce (score=0.0, i in c1 | score + (i[1]*10^(3-i[0]))) as reduced
> with idm, collect([idn,reduced]) as cr, sum(reduced) as sr 
> with idm,cr,size(cr) as lcr, sr where lcr>1
> with idm, cr, sr order by sr desc limit 5
> unwind cr as rel
> with idm as from,rel[0] as to,rel[1] as relscore
> return *;
> +--------------------------+
> | from  | relscore | to    |
> +--------------------------+
> | 30668 | 36.0     | 30688 |
> | 30668 | 2.0      | 27682 |
> | 30196 | 24.0     | 30688 |
> | 30196 | 1.0      | 27682 |
> +--------------------------+
> 4 rows
> 56 ms

now adding two MATCH statements at the end causes an error 

neo4j-sh (?)$ with  {selection} as collection

> match p=(n)-[_..3]-(m) 
> // no paths that pass through other nodes in the selection
> where 
>     id(n) in collection
>     and NOT (n IN TAIL(nodes(p)))
> with id(m) as idm,id(n) as idn,length(p) as lp, count(_) as count,collection order by idm,idn,lp asc
> with idm,idn,collect([lp,count]) as c1,collection
>    where NOT idm IN collection
> // weighing of paths.. each hop further a factor 10 less
> with idm,idn, c1,reduce (score=0.0, i in c1 | score + (i[1]*10^(3-i[0]))) as reduced
> with idm, collect([idn,reduced]) as cr, sum(reduced) as sr 
> with idm,cr,size(cr) as lcr, sr where lcr>1
> with idm, cr, sr order by sr desc limit 5
> unwind cr as rel
> with idm as from,rel[0] as to,rel[1] as relscore
> 
> match (n) where id(n)=from
> match (m) where id(m)=to
> return id(m),id(n);
> 57 ms

WARNING: Unexpected error during late semantic checking: Type mismatch: expected Collection<Integer> but was Collection<Number>

but when I replace the {selection} by static values, it does run again.

neo4j-sh (?)$ with  [30688,27682] as collection

> match p=(n)-[_..3]-(m) 
> // no paths that pass through other nodes in the selection
> where 
>     id(n) in collection
>     and NOT (n IN TAIL(nodes(p)))
> with id(m) as idm,id(n) as idn,length(p) as lp, count(_) as count,collection order by idm,idn,lp asc
> with idm,idn,collect([lp,count]) as c1,collection
>    where NOT idm IN collection
> // weighing of paths.. each hop further a factor 10 less
> with idm,idn, c1,reduce (score=0.0, i in c1 | score + (i[1]*10^(3-i[0]))) as reduced
> with idm, collect([idn,reduced]) as cr, sum(reduced) as sr 
> with idm,cr,size(cr) as lcr, sr where lcr>1
> with idm, cr, sr order by sr desc limit 5
> unwind cr as rel
> with idm as from,rel[0] as to,rel[1] as relscore
> 
> match (n) where id(n)=from
> match (m) where id(m)=to
> return id(m),id(n);
> +---------------+
> | id(m) | id(n) |
> +---------------+
> | 30688 | 30668 |
> | 27682 | 30668 |
> | 27682 | 30196 |
> | 30688 | 30196 |
> +---------------+
> 4 rows
> 246 ms

### PR DESCRIPTION
**Pull request by Mats-SX**
Fixes #5921

### CODE REVIEW

**Comment by cleishm** [comment]
Removing the type expectation seems heavy handed, especially as the expectation works ok with the rule planner or when parameters are substituted in: which means the expectation is ok. I assume it was also there in 2.2 which was ok?

**Comment by craigtaverner** [comment]
Chris, the issue started in 2.2.3. In 2.2.2 and before there was no expectation, mainly because a third round of semantic checking was only added in 2.2.3, and that round occurs after rewriting id(n)=x to id(n) in [x] and it turned out the type checking for IN is much more stringent than for '='. The PR is a proposal to be discussed (hence the 'not ready for merge'). We would prefer that type checking allow Int to be compatible with [Number], but it appears not to be the case (in either direction). Neither casting nor coercion is supported, and fixing that appears a deep refactoring.

File: community/cypher/cypher/src/test/scala/org/neo4j/cypher/EqualsTest.scala [hunk 1]
```diff
@@ -25,6 +25,57 @@ import org.scalatest.junit.JUnitRunner
 @RunWith(classOf[JUnitRunner])
 class EqualsTest extends ExecutionEngineFunSuite {
 
+  test("should not throw semantic check error for number-typed integer comparison") {
+    createNode()
+
+    // the parameter is used to disable auto-parametrization
+    val queryWithInt =
+      """PROFILE
+        |WITH {parameter} AS p
```
Comment (cleishm) [inline community/cypher/cypher/src/test/scala/org/neo4j/cypher/EqualsTest.scala:34]: Might be nice to add a planner option like `PROFILE autoparam=false ...`, which is explicit, rather than faking it by having a dummy parameter. Something to consider.

**Comment by cleishm** [comment]
@craigtaverner Ok. Although I still suggesting making it equivalent to what equals does, which is assert that the comparison is against CTAny against CTAny. That means the equivalent for `IN` would be CTAny against CTCollection(CTAny). In this case, you'd make that line `rhs.expectType(CTCollection(CTAny).covariant) chain`, which I happen to have already tested and verified passes the new tests you wrote.

**Comment by cleishm** [comment]
https://github.com/cleishm/neo4j/commit/85b91a8f3d3cc3a9e16b35af10f1684c74f932d8#diff-0a3a6439814d007f9ea8eb9518e61be2L103

File: community/cypher/cypher/src/test/scala/org/neo4j/cypher/EqualsTest.scala (hunk 1 above)
Comment (Mats-SX) [inline community/cypher/cypher/src/test/scala/org/neo4j/cypher/EqualsTest.scala:34]: Good idea, noted.

**Comment by Mats-SX** [comment]
@cleishm I implemented your fix in the PR and added a few tests that make sure that the semantic checking does not allow wrong types on the right-hand side, which our initial hack would've.

**Comment by cleishm** [comment]
@Mats-SX: +1
