### PR TITLE
Correct status code when using hint with no index

### LINKED ISSUE #5902: Regression: NoSuchIndex is now a DatabaseError
I can't seem to repro this on console.neo4j.org, but at least locally, running Neo4j 2.2.6, when I make the following query via the `/db/data/transaction` REST API:

``` cypher
MATCH (n:Test)
USING INDEX n:Test(foo)
WHERE n.foo = {foo}
RETURN n
```

I get back a `Neo.DatabaseError.Statement.ExecutionFailure` instead of what used to be a `Neo.ClientError.Schema.NoSuchIndex`.

The error message and stack trace (pretty-printed below) look like the underlying error is still the same; it maybe just isn't being properly handled?

```
org.neo4j.kernel.impl.query.QueryExecutionKernelException: No such index found.
Label: `Test`
Property name: `index_09002856723964214`
    at org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:65)
    at org.neo4j.server.rest.transactional.TransactionHandle.executeStatements(TransactionHandle.java:327)
    at org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:146)
    at org.neo4j.server.rest.web.TransactionalService$2.write(TransactionalService.java:211)
    at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
    at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
    at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.cypher.IndexHintException: No such index found.
Label: `Test`
Property name: `index_09002856723964214`
    at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.indexHintException(CompatibilityFor2_2.scala:102)
    at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.indexHintException(CompatibilityFor2_2.scala:53)
    at org.neo4j.cypher.internal.compiler.v2_2.IndexHintException.mapToPublic(CypherException.scala:92)
    at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.runSafely(CompatibilityFor2_2.scala:113)
    at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$$anon$2.plan(CompatibilityFor2_2.scala:159)
    at org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1$$anonfun$apply$1.apply(ExecutionEngine.scala:154)
    at org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1$$anonfun$apply$1.apply(ExecutionEngine.scala:151)
    at org.neo4j.cypher.internal.compiler.v2_2.MonitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:35)
    at org.neo4j.cypher.internal.compiler.v2_2.helpers.LRUCache.getOrElseUpdate(LRUCache.scala:34)
    at org.neo4j.cypher.internal.compiler.v2_2.helpers.LRUCache.apply(LRUCache.scala:64)
    at org.neo4j.cypher.internal.compiler.v2_2.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:33)
    at org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:151)
    at org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:151)
    at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at scala.collection.Iterator$$anon$13.next(Iterator.scala:372)
    at org.neo4j.cypher.ExecutionEngine.liftedTree1$1(ExecutionEngine.scala:163)
    at org.neo4j.cypher.ExecutionEngine.planQuery(ExecutionEngine.scala:143)
    at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:107)
    at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:102)
    at org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:61)
    ... 30 more
```

Not sure exactly when this regression happened. Also haven't tested with 2.2.7 or 2.3.x yet.

### PR DESCRIPTION
**Pull request by pontusmelke**
When using `USING INDEX` without there being any index the returned status
code should be a `Neo.ClientError.Schema.NoSuchIndex`

fixes #5902

### CODE REVIEW

File: community/server/src/test/java/org/neo4j/server/rest/transactional/integration/TransactionIT.java [hunk 1]
```diff
@@ -853,6 +852,15 @@ public void restFormattedNodesShouldHaveSensibleUrisWhenUsingXForwardHeader() th
                 "/node/\\d+/relationships/in/\\{-list\\|&\\|types\\}", hostname, scheme );
     }
 
+    @Test
+    public void correctStatusCodeWhenUsingHintWithoutAnyIndex() throws Exception
+    {
+        // begin and execute and commit
+        Response begin = http.POST( "/db/data/transaction/commit", quotedJson( "{ 'statements': [ { 'statement': " +
+                                                                               "'MATCH (n:Test) USING INDEX n:Test(foo) WHERE n.foo = {foo} RETURN n' } ] }" ) );
```
Comment (Mats-SX) [inline community/server/src/test/java/org/neo4j/server/rest/transactional/integration/TransactionIT.java]: How does this work? Where is the parameter `foo` sent over?
