### PR TITLE
Internal APIs to create tokens in batches.

### LINKED ISSUE #6955: [3.0-RC1] Creating a node with huge amount of properties causes application thread blocking forever
When creating a node with huge amount of properties, the application thread blocks forever

**Neo4j Version:** 3.0RC1
**Operating System:** Os X Yosemite 
**API:** Cypher with Java Bolt Driver
### Steps to reproduce

Fresh db, use the test snippet below, this test never returns and db hangs (also in browser)

Test snippet : 

``` java
@Test
    public void testMap16()
    {
        Map<String, Object> parameters = new HashMap<String, Object>();
        Map<String, String> properties = new HashMap<String, String>();
        for (int i = 0; i < 65530; ++i) {
            properties.put("key" + i, "value" + i);
        }
        parameters.put("props", properties);
        String query = "CREATE (n:TestMap) SET n += {props} RETURN n";

        Driver driver = GraphDatabase.driver(NEO4J_HOST);
        Session session = driver.session();
        StatementResult rs = session.run(query, parameters);
        rs.consume();
        session.close();
        driver.close();
    }
```
### Actual behavior

Output of `debug.log` : 

```
016-04-15 22:01:57.478+0000 INFO  [o.n.k.i.DiagnosticsManager] --- SERVER STARTED END ---
2016-04-15 22:03:06.660+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 301ms.
2016-04-15 22:03:08.299+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 214ms.
2016-04-15 22:05:30.881+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 699ms.
2016-04-15 22:05:31.689+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 397ms.
2016-04-15 22:05:35.497+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 206ms.
2016-04-15 22:05:35.813+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 215ms.
2016-04-15 22:05:42.261+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 266ms.
2016-04-15 22:05:44.616+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 204ms.
2016-04-15 22:05:47.419+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 415ms.
2016-04-15 22:05:49.649+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 206ms.
2016-04-15 22:05:58.011+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 217ms.
2016-04-15 22:06:00.413+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 232ms.
2016-04-15 22:06:06.062+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 270ms.
2016-04-15 22:06:06.813+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 239ms.
2016-04-15 22:06:39.573+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 246ms.
2016-04-15 22:06:52.400+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 234ms.
2016-04-15 22:06:53.767+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [53136]:  Starting check pointing...
2016-04-15 22:06:53.767+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [53136]:  Starting store flush...
2016-04-15 22:06:53.794+0000 INFO  [o.n.k.i.s.c.CountsTracker] About to rotate counts store at transaction 53138 to [/Users/ikwattro/dev/_graphs/RC1/data/databases/graph.db/neostore.counts.db.b], from [/Users/ikwattro/dev/_graphs/RC1/data/databases/graph.db/neostore.counts.db.a].
2016-04-15 22:06:53.796+0000 INFO  [o.n.k.i.s.c.CountsTracker] Successfully rotated counts store at transaction 53138 to [/Users/ikwattro/dev/_graphs/RC1/data/databases/graph.db/neostore.counts.db.b], from [/Users/ikwattro/dev/_graphs/RC1/data/databases/graph.db/neostore.counts.db.a].
2016-04-15 22:06:53.825+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [53136]:  Store flush completed
2016-04-15 22:06:53.825+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [53136]:  Starting appending check point entry into the tx log...
2016-04-15 22:06:53.826+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [53136]:  Appending check point entry into the tx log completed
2016-04-15 22:06:53.826+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [53136]:  Check pointing completed
2016-04-15 22:06:53.826+0000 INFO  [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [0]:  Starting log pruning.
2016-04-15 22:06:53.826+0000 INFO  [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [0]:  Log pruning complete.
2016-04-15 22:07:00.310+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 212ms.
2016-04-15 22:07:16.768+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 204ms.
2016-04-15 22:07:18.307+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 228ms.
2016-04-15 22:07:23.290+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 233ms.
2016-04-15 22:07:42.999+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 202ms.
2016-04-15 22:07:44.763+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 201ms.
```

Partial output with jvmtop : 

```
 JvmTop 0.8.0 alpha - 00:08:17, x86_64,  4 cpus, Mac OS X 10.11., load avg 6.79
 http://code.google.com/p/jvmtop

 Profiling PID 7018: org.neo4j.server.enterprise.EnterpriseEn

  94.76% (   232.27s) org.neo4j.kernel.impl.util.CopyOnWriteHashMap.copy()
   3.33% (     8.16s) org.neo4j.io.fs.StoreFileChannel.force()
   0.43% (     1.06s) org.neo4j.io.fs.StoreFileChannel.write()
   0.11% (     0.26s) ....neo4j.cypher.internal.spi.v3_0.TransactionBoundQuery()
   0.10% (     0.25s) io.netty.channel.nio.NioEventLoop.select()
   0.09% (     0.21s) org.neo4j.kernel.impl.api.store.SchemaCache.constraints()
   0.08% (     0.20s) ....neo4j.kernel.impl.transaction.command.Command$Proper()
   0.08% (     0.19s) ....neo4j.kernel.impl.api.BatchTransactionApplierFacade.()
   0.06% (     0.16s) ....neo4j.io.pagecache.impl.muninn.CursorPool.takeWriteC()
   0.06% (     0.15s) org.neo4j.collection.pool.LinkedQueuePool.acquire()
   0.06% (     0.14s) ....neo4j.kernel.impl.store.MetaDataStore.transactionClo()
   0.06% (     0.14s) scala.collection.immutable.HashMap$HashTrieMap.updated0()
   0.05% (     0.13s) ....neo4j.kernel.impl.transaction.log.PhysicalFlushableC()
   0.05% (     0.13s) org.neo4j.string.UTF8.encode()
   0.05% (     0.13s) ....neo4j.kernel.impl.store.record.TokenRecord.addNameRe()
   0.05% (     0.13s) ....neo4j.kernel.impl.store.record.AbstractBaseRecord.<i()
   0.05% (     0.13s) org.neo4j.kernel.impl.api.KernelStatement.txState()
   0.05% (     0.13s) scala.runtime.BoxesRunTime.hashFromNumber()
   0.05% (     0.11s) org.neo4j.kernel.impl.api.TransactionApplierFacade.close()
   0.04% (     0.11s) org.neo4j.kernel.impl.util.CopyOnWriteHashMap.get()
 JvmTop 0.8.0 alpha - 00:08:18, x86_64,  4 cpus, Mac OS X 10.11., load avg 6.79
 http://code.google.com/p/jvmtop

 Profiling PID 7018: org.neo4j.server.enterprise.EnterpriseEn

  94.77% (   233.05s) org.neo4j.kernel.impl.util.CopyOnWriteHashMap.copy()
   3.32% (     8.16s) org.neo4j.io.fs.StoreFileChannel.force()
   0.43% (     1.06s) org.neo4j.io.fs.StoreFileChannel.write()
   0.11% (     0.26s) ....neo4j.cypher.internal.spi.v3_0.TransactionBoundQuery()
   0.10% (     0.25s) io.netty.channel.nio.NioEventLoop.select()
   0.09% (     0.21s) org.neo4j.kernel.impl.api.store.SchemaCache.constraints()
   0.08% (     0.20s) ....neo4j.kernel.impl.transaction.command.Command$Proper()
   0.08% (     0.19s) ....neo4j.kernel.impl.api.BatchTransactionApplierFacade.()
   0.06% (     0.16s) ....neo4j.io.pagecache.impl.muninn.CursorPool.takeWriteC()
   0.06% (     0.15s) org.neo4j.collection.pool.LinkedQueuePool.acquire()
   0.06% (     0.14s) ....neo4j.kernel.impl.store.MetaDataStore.transactionClo()
   0.06% (     0.14s) scala.collection.immutable.HashMap$HashTrieMap.updated0()
   0.05% (     0.13s) ....neo4j.kernel.impl.transaction.log.PhysicalFlushableC()
   0.05% (     0.13s) org.neo4j.string.UTF8.encode()
   0.05% (     0.13s) ....neo4j.kernel.impl.store.record.TokenRecord.addNameRe()
   0.05% (     0.13s) ....neo4j.kernel.impl.store.record.AbstractBaseRecord.<i()
   0.05% (     0.13s) org.neo4j.kernel.impl.api.KernelStatement.txState()
   0.05% (     0.13s) scala.runtime.BoxesRunTime.hashFromNumber()
   0.05% (     0.11s) org.neo4j.kernel.impl.api.TransactionApplierFacade.close()
   0.04% (     0.11s) org.neo4j.kernel.impl.util.CopyOnWriteHashMap.get()
 JvmTop 0.8.0 alpha - 00:08:19, x86_64,  4 cpus, Mac OS X 10.11., load avg 6.79
 http://code.google.com/p/jvmtop

 Profiling PID 7018: org.neo4j.server.enterprise.EnterpriseEn

  94.79% (   233.74s) org.neo4j.kernel.impl.util.CopyOnWriteHashMap.copy()
   3.31% (     8.17s) org.neo4j.io.fs.StoreFileChannel.force()
   0.43% (     1.06s) org.neo4j.io.fs.StoreFileChannel.write()
   0.11% (     0.26s) ....neo4j.cypher.internal.spi.v3_0.TransactionBoundQuery()
   0.10% (     0.25s) io.netty.channel.nio.NioEventLoop.select()
   0.08% (     0.21s) org.neo4j.kernel.impl.api.store.SchemaCache.constraints()
   0.08% (     0.20s) ....neo4j.kernel.impl.transaction.command.Command$Proper()
   0.08% (     0.19s) ....neo4j.kernel.impl.api.BatchTransactionApplierFacade.()
   0.06% (     0.16s) ....neo4j.io.pagecache.impl.muninn.CursorPool.takeWriteC()
   0.06% (     0.15s) org.neo4j.collection.pool.LinkedQueuePool.acquire()
   0.06% (     0.14s) ....neo4j.kernel.impl.store.MetaDataStore.transactionClo()
   0.06% (     0.14s) scala.collection.immutable.HashMap$HashTrieMap.updated0()
   0.05% (     0.13s) ....neo4j.kernel.impl.transaction.log.PhysicalFlushableC()
   0.05% (     0.13s) org.neo4j.string.UTF8.encode()
   0.05% (     0.13s) ....neo4j.kernel.impl.store.record.TokenRecord.addNameRe()
   0.05% (     0.13s) ....neo4j.kernel.impl.store.record.AbstractBaseRecord.<i()
   0.05% (     0.13s) org.neo4j.kernel.impl.api.KernelStatement.txState()
   0.05% (     0.13s) scala.runtime.BoxesRunTime.hashFromNumber()
   0.05% (     0.11s) org.neo4j.kernel.impl.api.TransactionApplierFacade.close()
   0.04% (     0.11s) org.neo4j.kernel.impl.util.CopyOnWriteHashMap.get()
 JvmTop 0.8.0 alpha - 00:08:20, x86_64,  4 cpus, Mac OS X 10.11., load avg 6.48
 http://code.google.com/p/jvmtop

 Profiling PID 7018: org.neo4j.server.enterprise.EnterpriseEn
```

### PR DESCRIPTION
**Pull request by chrisvest**
Previously we have always created each token in their own internal (implicit) transaction. These APIs allows us to create multiple tokens of a given type in one implicit transaction.

With support for this on the Cypher side of things, we should be able to fix #6955.

### CODE REVIEW

**Comment by chrisvest** [comment]
At this point only the labels can be batch-created via the Core API, and none of the token types are created via Cypher.

File: community/kernel/src/main/java/org/neo4j/kernel/impl/core/DelegatingTokenHolder.java [hunk 1]
```diff
@@ -112,6 +119,79 @@ private synchronized int createToken( String name ) throws KernelException
...
+        }
+        return foundUnresolvable;
+    }
+
+    private synchronized void createMissingTokens( String[] names, int[] ids )
+    {
+        // We redo the resolving under the lock, to make sure that these ids are really missing, and won't be
+        // created concurrently with us.
+        PrimitiveIntSet unresolvedIndexes = Primitive.intSet();
+        resolveIds( names, ids, i -> !unresolvedIndexes.add( i ) );
```
Comment (tinwelint) [inline community/kernel/src/main/java/org/neo4j/kernel/impl/core/DelegatingTokenHolder.java]: A name duplicate would make resolveIds stop early, which would result in not all names being resolved/created. Problem?

**Review by tinwelint — APPROVED** [review]
Looks nice, and true clustering support can be added later I'd guess w/ protocol addition/change and all that

File: community/kernel/src/main/java/org/neo4j/kernel/impl/core/DelegatingTokenHolder.java [hunk 2]
```diff
@@ -112,6 +121,76 @@ private synchronized int createToken( String name ) throws KernelException
...
+        }
+        return foundUnresolvable;
+    }
+
+    private synchronized void createMissingTokens( String[] names, int[] ids )
+    {
+        // We redo the resolving under the lock, to make sure that these ids are really missing, and won't be
+        // created concurrently with us.
+        MutableIntSet unresolvedIndexes = new IntHashSet();
+        resolveIds( names, ids, i -> !unresolvedIndexes.add( i ) );
```
Comment (tinwelint) [inline community/kernel/src/main/java/org/neo4j/kernel/impl/core/DelegatingTokenHolder.java:170]: A name duplicate would make resolveIds stop early, which would result in not all names being resolved/created. Problem?

Comment (chrisvest) [reply community/kernel/src/main/java/org/neo4j/kernel/impl/core/DelegatingTokenHolder.java:170]: And if we pass it through… might duplicate unresolved names be created twice? I'm conflicted about whether to handle it, or document that there must be no duplicates. Any opinions from @systay or @fickludd?

Comment (fickludd) [reply community/kernel/src/main/java/org/neo4j/kernel/impl/core/DelegatingTokenHolder.java:170]: I don't know how Cypher would use this batching atm. In the situation described in the github issue we would be guaranteed to not have to duplicates because the properties are provided in a map. 

It feels to me like handling duplicates nicely will be a small cost compared to the issue we are solving, so maybe just handle it?

Comment (chrisvest) [reply community/kernel/src/main/java/org/neo4j/kernel/impl/core/DelegatingTokenHolder.java:170]: This particular call won't stop early, because we are storing array indexes into the set, and they are obviously always unique.

I have made `createUnresolvedTokens` handle any duplicates it might come across. Please take another look.
