### PR TITLE
Fix bug in query cache key.

### LINKED ISSUE #11490: multiple spaces in query not work
## Guidelines

- Neo4j version: 3.3.0
- Operating system: MAC OSX
- **Steps to reproduce**
- Expected behavior
- Actual behavior

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

---

## example 1
1. `neo4j-shell`
2. `RETURN LENGTH('1 2') AS L1;`
3. `RETURN LENGTH('1            2') AS L1;`

there`re **multiple spaces** between 1 and 2;

both results

```
+----+
| L1 |
+----+
| 3  |
+----+
```

---
## example 2
```
CREATE (:TEST{TEST_ID:'1 2'});
CREATE (:TEST{TEST_ID:'1  2'});
CREATE CONSTRAINT ON (n:TEST) ASSERT n.TEST_ID IS UNIQUE;
```
result is 
```
WARNING: Unable to create CONSTRAINT ON ( test:TEST ) ASSERT test.TEST_ID IS UNIQUE:
Both Node(108) and Node(148) have the label `TEST` and property `TEST_ID` = '1 2'
```
it seems that the spaces in the strings  don`t work?

### PR DESCRIPTION
**Pull request by Lojjs**
Fixes #11490, so the query cache key doesn't remove sequential spaces

### CODE REVIEW

File: community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/CypherCompiler.scala [hunk 1]
```diff
@@ -58,7 +58,7 @@ case class PreParsedQuery(statement: String, rawStatement: String, version: Cyph
       case _ => s"strategy=${updateStrategy.name}"
     }
 
-    s"CYPHER ${version.name} $plannerInfo $runtimeInfo $updateStrategyInfo $statement".replaceAll("\\s+", " ")
+    s"CYPHER ${version.name} $plannerInfo $runtimeInfo $updateStrategyInfo $statement"
```
Comment (fickludd) [inline community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/CypherCompiler.scala:61]: I guess this change fixes the problem with string literals, but it will have the drawback the two identical queries which only differ in a white-space will be planned separately and take 2 query cache slots. 

It's of course better to return the correct results, that to use less planning time, but if we were to solve both we probably would need to parse the query and rebuild from AST.

**Review by fickludd — APPROVED** [review]
Interesting bug. Clean fix.
