### PR TITLE
Fix online backup of read-only instances with schema and legacy indexes.

### LINKED ISSUE #10089: Database backup fails in read-only mode
The command `neo4j-admin backup` fails if the database being backed up is in read-only mode.

**Neo4j Version:** 3.2.2 (Enterprise)
**Operating System:** Tested with the database running on Ubuntu 16.04, neo4j-admin was tested from Ubuntu 16.04 and Windows 10 v1703
**API:** neo4j-admin

### Steps to reproduce
1. Run neo4j-admin backup, pointed at a running database (either remotely or from the same machine)

### Expected behavior
It should create a backup of the running database

### Actual behavior
It fails with the following output:
`Doing full backup...`
`command failed: Backup failed: Unable to force ContractCheckingIndexProxy -> OnlineIndexProxy[accessor:org.neo4j.kernel.api.impl.schema.LuceneIndexAccessor@ae4d8a8, descriptor:Index( GENERAL, :label[39](property[51]) )]`

### PR DESCRIPTION
**Pull request by chrisvest**
Taking an online backup of a read-only instance would previously throw a variety of exceptions, depending on its schema/legacy indexes. This fixes #10089.

This also fixes a plurality of bugs where create and drop of legacy indexes are concurrent with commits of changes to those indexes. These bugs had snuck in because the relevant test didn't have a proper test-name, and thus the test was never run by our build system.

Also fixed in this PR, is a bug in _relationship_ legacy indexes, where changes could be committed with different document types. This was already fixed for node indexes a long time ago, but that fix was apparently never applied to the relationship indexes.

### CODE REVIEW

File: community/lucene-index/src/main/java/org/neo4j/index/impl/lucene/legacy/LuceneCommandApplier.java [hunk 1]
```diff
@@ -72,46 +73,67 @@ public boolean visitIndexAddRelationshipCommand( AddRelationshipCommand command
...
+            // not be able to recover, which is why this check is here.
+            if ( value != null )
+            {
+                context.ensureWriterInstantiated();
+                context.indexType.addToDocument( context.getDocument( entityId, true ).document, key, value );
+            }
+        }
+        catch ( LegacyIndexNotFoundKernelException ignore )
+        {
+            // Pretend the index never existed.
```
Comment (tinwelint) [inline community/lucene-index/src/main/java/org/neo4j/index/impl/lucene/legacy/LuceneCommandApplier.java:96]: Useful for recovery, or when could an index just disappear like that?

**Review by tinwelint — COMMENTED** [review]
Looks great. I have one little question.

File: community/lucene-index/src/main/java/org/neo4j/index/impl/lucene/legacy/LuceneCommandApplier.java (hunk 1 above)
Comment (chrisvest) [reply community/lucene-index/src/main/java/org/neo4j/index/impl/lucene/legacy/LuceneCommandApplier.java:96]: As far as I can tell, there is locking to make legacy index configuration changes mutually exclusive with updates to those indexes, so legacy indexes can basically be dropped at any time.

What happens here is that we ignore updates that were slated for indexes that are dropped concurrently with our commit. Previously, this would have thrown some sort of RuntimeException.

Comment (tinwelint) [reply community/lucene-index/src/main/java/org/neo4j/index/impl/lucene/legacy/LuceneCommandApplier.java:96]: I'm absolutely certain you meant to say _...there is NO locking to make legacy index..._. OK then I understand.

**Review by tinwelint — APPROVED** [review]

File: community/lucene-index/src/main/java/org/neo4j/index/impl/lucene/legacy/LuceneCommandApplier.java (hunk 1 above)
Comment (chrisvest) [reply community/lucene-index/src/main/java/org/neo4j/index/impl/lucene/legacy/LuceneCommandApplier.java:96]: Yes, that's exactly what I meant to say. Somehow that important little detail didn't make it from my brain to my fingers.
